### ISSUE TITLE
Does the current SQS implementation support same sqs queue name at different regions.

### ISSUE THREAD

**Issue by philipsamuel** [Netflix/conductor#1012]
Scenario : 
Two queues with the same name in two AWS regions
Can the SQS implementation in conductor listen to both, atleast using two event handlers.

**Comment by apanicker-nflx** [comment]
The current implementation in conductor can only listen to SQS queues in the same region that conductor is deployed in. 
If you have a pressing need for this feature, please feel free to submit a PR with the implementation and we will be happy to review and merge.
A couple of possible implementation options could be:
- Implement a SQS client factory (instead of SQS client) which can be configured to listen to queues in different regions
- Use the queue ARN instead of the queue name to configure the listener.
