### ISSUE TITLE
Eventhandler - Unmatched condition

### ISSUE THREAD

**Issue by jkaipa** [Netflix/conductor#1046]
I have a event handler listening on to a sink (queue). When a message is published into the queue the message is getting vanished even if the condition in the handler is evaluated to false. Shouldn't EventProcessor reject the message in this scenario?

**Comment by apanicker-nflx** [comment]
Seems like this is because the message is acked on the queue [here](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/events/EventProcessor.java#L155). Since the condition is not met, the message is not executed and this message is then acked (deleted from the queue). The EventProcessor is essentially "rejecting" this message in this scenario such that the message is not actually executed (i.e. the actions configured for the event handler are not executed).

**Comment by jkaipa** [comment]
@apanicker-nflx Is it not better to reject such a message if none of the handlers are matching the condition? If the message is rejected instead of ack, the publisher would have the ability to track such failed messages and can take further action.

**Comment by apanicker-nflx** [comment]
There is an argument to be made here that acking the message on the queue is useful, otherwise the queue would be bloated by messages that have been rejected and the event handler would just keep trying to re-process these messages thus reducing the throughput of the system. 
You could essentially change this behavior in your implementation if you choose to do so by setting the [republishIfNoAck](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/events/queue/ObservableQueue.java#L68-L77) flag on the queue to true. This would ensure that the event processor republishes the message back to the queue if the message processing fails.
