### ISSUE TITLE
Optional Task

### ISSUE THREAD

**Issue by andrea11** [Netflix/conductor#1060]
Hello,
I was testing the functionality of "optional" set for a task. I was wondering why an optional task should not retry and pass to COMPLETED_WITH_ERRORS only when all retries failed.
Do you agree with this behaviour? Or the current one is working as expected?

Thank you

**Comment by apanicker-nflx** [comment]
Currently, the contract of an optional task within Conductor is that the task failure is considered harmless for workflow execution and the workflow is allowed to progress in such a scenario. Retrying such a task is not considered as necessary and retries are skipped.

**Comment by andrea11** [comment]
Thanks for your reply. However, I was wondering if this behaviour could be change. I agree with you with the harmless of an optional task, but I think that it should not have consequences on the retry policy. Will not be better to have another option at workflow task such as "skipRetry", that could be use together with the optional to preserve the current behaviour?
What do you think?

**Comment by mohelsaka** [comment]
We have noticed the behavior of OPTIONAL tasks and it was a bit surprising to us that it didn't follow the retry policy.
I think if OPTIONAL task got retried, it won't really break the contract of "optional task is considered harmless for workflow" as long as the workflow continues execution normally.

On the other hand, the current behavior comes with the cost of making our workflows definitions complicated, because we had to build some wrapper workflows around optional tasks to make them retriable from some other parent workflow.

We're working at the moment on making some code change in conductor to change that default behavior, we'll push a merge request with it once it's done.

**Comment by apanicker-nflx** [comment]
@andrea11 and @mohelsaka Thanks for the suggestions. I agree that the `optional` tasks can be retried upon failure and can eventually be considered harmless to workflow execution if all retries fail. This would be a nice-to-have enhancement on the current optional task implementation.
Looking forward to your pull request @mohelsaka .
