### ISSUE TITLE
Questions on SQS implementation

### ISSUE THREAD

**Issue by dskarataev** [Netflix/conductor#1092]
Hello,

we faced 2 issues with the SQS implementation and both of them are related to losing messages.

1. when we add a new EventHandler, it will automatically subscribe to the queue and receive messages from this queue, but when we remove or disable the EventHandler and there are no other EventHandlers that are listening to the same queue, Conductor still consumes and acknowledges messages so the messages just disappear from the queue in that case and go to nowhere

2. inside the SQS implementation there are many places where the message is acknowledged in error cases, why?

Usually, message should be acknowledged only when the job related to the message is successfully done and should stay in the queue not being lost when there is some problem, but we see a totally opposite approach in the SQS implementation of Conductor.

Before fixing it, we would like to make sure first that we are going to do it properly, so we would be really happy to hear your comments about these issues. Thank you!

**Comment by kishorebanala** [comment]
Hey @dskarataev, you're right. If you look here: https://github.com/Netflix/conductor/blob/master/contribs/src/main/java/com/netflix/conductor/contribs/queue/QueueManager.java#L115, Conductor would just ack the message and do nothing when task is not found for event handler to run.

In order to improve this, the queue should know that at some point in future a task will be created for that message, and it's okay to keep the message. If not, say if the workflow terminates before the task for that event is created, the message would remain in queue for ever.

A cleaner implementation would make this behavior of keeping the msg queue vs discarding configurable, and considers all other scenarios to find right balance between waiting for the task to be available vs removing dead messages from queue.

Please start a conversation with you approach and we can finalize on the implementation details. Thanks again for your contributions.

**Comment by dskarataev** [comment]
@kishorebanala how about this one?

inside the SQS implementation there are many places where the message is acknowledged in error cases, why?
