### ISSUE TITLE
Don’t terminate other fork tasks when one of them failed 

### ISSUE THREAD

**Issue by HenryLauu** [Netflix/conductor#1101]
I am having an daynamic form join workflow , when one of the fork task failed, other task s are transferred to terminate status, how can I keep other task working and finally failed on join task?

**Comment by jkaipa** [comment]
When one task is failed, the rest of them which are part of the same fork are cancelled.

**Comment by HenryLauu** [comment]
If I don't want to cancelled other tasks, how can I do that?

**Comment by apanicker-nflx** [comment]
@HenryLauu In order to not terminate the other fork tasks when one fork fails, you can mark all fork tasks as [`optional`](https://netflix.github.io/conductor/configuration/workflowdef/#tasks-within-workflow). This will ensure that the workflow will progress even if a fork task fails. 

You can still choose to fail this workflow after the JOIN task, by adding a LAMBDA task after the JOIN which evaluates the status of each fork.

**Comment by HenryLauu** [comment]
hi @apanicker-nflx . Any suggestions or document reference about how to check the status of forked task with lambda task?
