### ISSUE TITLE
Lambda Task remain in "SCHEDULED" state

### ISSUE THREAD

**Issue by ketantalreja** [Netflix/conductor#1173]
Hi, I am working on a POC and using Netflix conductor as an orchestration engine, I am using Lambda task in Conductor for evaluating expressions but the taskStatus always remain in SCHEDULED state, Could you please help?

Workflow Definition:

{"name": "Notification-Lambda", "tasks": [{"name": "decision_4", "type": "DECISION", "decisionCases": {"true": [{"name": "func_17", "type": "LAMBDA", "inputParameters": {"lambdaValue": "${workflow.input.age}", "scriptExpression": "if($.lambdaValue <= 18 ) { return { messages: ['Age_Not_Available'] } }"}, "taskReferenceName": "func_17"}]}, "caseExpression": "$.input_param_1 == 'CR' || $.input_param_1 == 'DX'", "inputParameters": {"input_param_1": "${workflow.input.study.series[0].modality}"}, "taskReferenceName": "decision_4"}], "version": 1, "description": "Notification-Lambda", "schemaVersion": 2, "outputParameters": {}}"

Conductor Execution log: 

{
  "taskType": "LAMBDA",
  "status": "SCHEDULED",
  "inputData": {
    "lambdaValue": 37,
    "scriptExpression": "if ($.lambdaValue <= 18) { return { messages: ['Age_Not_Available'] } }"
  },
  "referenceTaskName": "func_17",
  "retryCount": 0,
  "seq": 2,
  "pollCount": 0,
  "taskDefName": "21e4d4f2-adaf-4dd6-95a7-597d9fa2db30_func_17",
  "scheduledTime": 1559267660175,
  "startTime": 0,
  "endTime": 0,
  "updateTime": 1559267660179,
  "startDelayInSeconds": 0,
  "retried": false,
  "executed": false,
  "callbackFromWorker": true,
  "responseTimeoutSeconds": 0,
  "workflowInstanceId": "6aaf4a2b-3199-492a-9053-900c2ca32cae",
  "workflowType": "21e4d4f2-adaf-4dd6-95a7-597d9fa2db30",
  "taskId": "3479db58-3361-43f9-bd35-ffa174e749b0",
  "callbackAfterSeconds": 0,
  "workflowTask": {
    "name": "21e4d4f2-adaf-4dd6-95a7-597d9fa2db30_func_17",
    "taskReferenceName": "func_17",
    "inputParameters": {
      "lambdaValue": "${workflow.input.age}",
      "scriptExpression": "if ($.lambdaValue <= 18) { return { messages: ['Age_Not_Available'] } }"
    },
    "type": "LAMBDA",
    "startDelay": 0
  },
  "taskStatus": "SCHEDULED",
  "queueWaitTime": 0
}

**Comment by kishorebanala** [comment]
Hi @ketantalreja,  I tried running your workflow definition and couldn't reproduce the issue. Lambda task should be executed immediately by Conductor server. Since it is not an async system task, it is not added to queue for System task workers to execute. Unless there is some exception that prevents the decider to call `execute` on this task, it shouldn't remain in scheduled state.

Do you see any other System tasks remaining in SCHEDULED state? or any exceptions when this happens? Also, is this transient? Can you ensure that you're running latest version of Conductor please. Can you also try with a very simple use case of just a lambda task in the workflow without decides and any other logic. Thanks.

**Comment by ketantalreja** [comment]
Thanks @kishorebanala for the updates. 
Yes, I realized, that Lambda System task in only going to work from Conductor 2.8.x version onwards, whereas I was using Conductor 1.10.x version for running Lambda task in workflow definition. After upgrading to version 2.10.x, now I am able to execute Lambda task successfully. 
Thanks!!

**Comment by ketantalreja** [comment]
Closing this issue after upgrading Conductor version to 2.10.x

Thanks!!
