### ISSUE TITLE
require Docker images

### ISSUE THREAD

**Issue by SudheerD231** [Netflix/conductor#1189]
Require docker images to work on Conductor in my environment. Could you please provide the link to the docker images of the conductor. 

Thank you,

**Comment by demichej** [comment]
@SudheerD231 You need to build them currently yourself. There's a docker directory you can go into and run `docker-compose build`. That will build the images for you. 

I think the reason you need to do this is because you need to setup your own config.properties that are built into the image.

@apanicker-nflx another enhancement idea I had was to allow all the properties in the config.properties to be environment variables instead of config properties only. Wouldn't this allow for y'all to put Docker images in say the Netflix OSS Docker space for every version? And then people could use those images and use environment variables instead?

**Comment by apanicker-nflx** [comment]
@SudheerD231 Please build the docker images from the docker directory as suggested. Thanks for the response @demichej. 

We will look into changing the configs to env variables and publish docker images.
