### ISSUE TITLE
Failed indexing in Elasticsearch

### ISSUE THREAD

**Issue by clari-akhilesh** [Netflix/conductor#1211]
We have been running Conductor in our production environment for a while now. We're running about 1k workflows every minute. In order to not exhaust Redis and ES memory we rely on ES to perform the search and delete the workflows regularly. However, not all workflows and tasks are indexed successfully. We see a lot of these errors:
`Indexing failed for conductor, task`
`Indexing failed for conductor, workflow`
We're wondering what might be causing this. We're running 3 masters and 2 data nodes in our ES cluster. ES should be able to handle this load. Can you please provide some insight into what might be going wrong here?

**Comment by apanicker-nflx** [comment]
Please provide the stack trace accompanying the error to help identify the issue.

**Comment by clari-akhilesh** [comment]
Unfortunately, conductor code swallows the stack trace. The above messages are the only logs displayed.

**Comment by kishorebanala** [comment]
Hey @clari-akhilesh, It's hard to tell what's going on without full stack trace, especially because this is from an extension. From what you've mentioned, the failures are transient, and this could happen with ES when the indexing doc doesn't match the index template. From your local, may be you can debug by trying to index with one of the known failed docs.
