### ISSUE TITLE
Question related to HA setup

### ISSUE THREAD

**Issue by angladem** [Netflix/conductor#1214]
Hi, 

I have a question related to dyno queues. We are trying to setup a Conductor platform with the following : 
ES => shared index 
Dynomite : 2 rack of one node each (RF2, no sharding) 
Conductor : 2 servers 

Everything is in-house. 

In order to set all this up we defined 2 Dynomite racks us-east-1a/1b. Due to this, the queues are sharded according to these AZ. The issue I'm facing is the following : 
Conductor server 1 is configured for AZ 1a thus it consumes the "a" queue shard, the second server is configured for AZ 1b and consumes the b queue shard. 

We used 2 Conductor servers for resiliency in the first place, but since each of them is consuming only one shard of the queues, if one of them is in failure, the failover will happen on the Dynomite rack but not on the queue shard since it is determined by the EC2_AVAILABILITY_ZONE. 

Did I understood the situation properly ? Is there any solution that would not involve to have 2 Conductor server / AZ in order to obtain resiliency ? 

Thanks

**Comment by apanicker-nflx** [comment]
This is correct, polling from the queues is constrained by the EC2_AVAILABILITY_ZONE. This is a limitation enforced by dyno-queues.

@smukil / @rsrinivasanNetflix Can you please chime in to suggest any workarounds for this?

**Comment by rsrinivasanNetflix** [comment]
Yes, this is correct. The assumption would be that the shard will get consumed when the second instance comes back up in zone b. We currently keep the shards having access from the local zone only since that way the different zones can pop messages without the need for locking. @smukil has added a unsafe pop api in the latest dyno-queeues but I do not think conductor makes use of that since it removes the guarantee that the messages will not be duplicated.

**Comment by angladem** [comment]
Thanks for your feedbacks.
