### ISSUE TITLE
Complete action for external task

### ISSUE THREAD

**Issue by clari-akhilesh** [Netflix/conductor#127]
I have an event task in workflow1 which writes an event to complete a task in an instance of workflow2. Is it possible to do this? How do I get the workflowID of workflow2?

```
{
    "action": "complete_task",
    "complete_task": {
      "workflowId": "${source.externalId.workflowId}",   --i'm assuming this gives the workflowID of the workflow firing the event
      "taskRefName": "task_1",
      "output": {
        "response": "${source.result}"
      }
    },
    "expandInlineJSON": true
}
```

**Comment by v1r3n** [comment]
That will work, but the workflow1's event task will have to publish the id of the workflow2.  If you can  do that, then it should be possible.

**Comment by clari-akhilesh** [comment]
How do I get the ID of workflow2 in workflow1? Let's assume workflow2 was started by workflow1

**Comment by v1r3n** [comment]
If you have a task, that starts workflow2, then that task can produce an output with the id of the workflow2.  e.g. the task's output might look like:

```
{
"workflow2Id": "id of the workflow2"
}
```

In your event, you can use task's workflow2Id output as one of the payload to publish it.

**Comment by clari-akhilesh** [comment]
So assuming I have an event task which like this:
```
{
      "name": "event_task1",
      "taskReferenceName": "event_task1",
      "inputParameters": {
        "sink": "conductor:workflow1:event_task1",
        "ref_workflow": "workflow2"
      },
      "type": "EVENT"
    }
```

And the corresponding event handler:
```
{
  "name" : "crawl2 handler",
  "event": "conductor:workflow1:event_task1",
  "condition": "1>0",
  "actions": [{
    "action": "start_workflow",
    "start_workflow": {
      "name": $.ref_workflow,
      "input": {}
    }
  }]
}
```

Can you show me what output parameters, I should add to get the workflowID of workflow2?

**Comment by v1r3n** [comment]
The config above will only start the workflow2, but will not capture the id of the workflow2 into the event task.  The reason is that events are decoupled from handlers - and there could be multiple handlers listening on the events.  

If you want to capture the workflow2 details, you need to start the workflow.  

If you want to start workflow2 from workflow1, then the better option is to use it as SUB_WORKFLOW.  The sub workflow task will wait until the workflow2 completes, without any events/handlers.   You can have a fork with one branch starting workflow2 and another branch carrying on with other tasks, and have a join somewhere at the end where you want these two branches to merge.

**Comment by clari-akhilesh** [comment]
Thank you for the clarification.
