### ISSUE TITLE
Elasticsearch Rollover & Workflow Archival Questions

### ISSUE THREAD

**Issue by indiv0** [Netflix/conductor#1294]
Hello!

I was wondering how you guys handle archival and Elasticsearch rollover concerns.
1. I see that there is a `IndexDAO::searchArchivableWorkflows` method, but it doesn't appear to be used outside of tests, and has no equivalent REST/gRPC API. Are we meant to use this method via additional modules that we define?
2. There is a `WorkflowArchiveDAO`, but it doesn't seem to be used. Is this a legacy DAO which hasn't been removed, or are we supposed to implement/use it manually?
3. If I rollover an Elasticsearch index between archivals of workflows, what happens? Do workflows that are in Redis but no longer appear in Elasticsearch get archived correctly if I just `IndexDAO::searchArchivableWorkflows` and `ExecutionService::removeWorkflow(..., true)` after that?
4. More generally, do you guys have some recommendations regarding aliasing and/or rollover of Elasticsearch indices without breaking archival functionality?

**Comment by apanicker-nflx** [comment]
Hi @indiv0 
1. We use an additional module for workflow archival, which calls `searchArchivableWorkflows` to get all the terminal state workflows and calls `removeWorkflow(..., true)` to delete from primary store and index in ES with a rawJSON field.
2. Your observation is correct, this is a legacy DAO which we will mark as deprecated and remove soon.
3. Currently, we do not have a clean way of using index rollovers when archiving workflows. Instead, we run a cleanup job which deletes documents from our index which have not been updated for >1 year.
4. Since conductor updates documents in Elasticsearch, we are unable to use the rollover feature of ES (https://stackoverflow.com/questions/41830404/updating-existing-documents-in-elasticsearch-es-while-using-rollover-api). Instead, we use one index and cleanup documents periodically.

**Comment by indiv0** [comment]
Thank you for the thorough answer! Very useful information; should be sufficient to address my current use-case.

**Comment by rakeshnarang5** [comment]
@apanicker-nflx
"Currently, we do not have a clean way of using index rollovers when archiving workflows. Instead, we run a cleanup job which deletes documents from our index which have not been updated for >1 year."
Is this time configurable?
I want to configure this job such that it clean ups documents which have not been update for >30 days.
Is that possible?

**Comment by apanicker-nflx** [comment]
Hi @rakeshnarang5 , the cleanup job is a simple batch job which uses the elasticsearch [delete-by-query](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-delete-by-query.html) API to perform the deletion of documents from the index. This time can be configured in the request body as required.

PS: Please create a new issue/discussion for further conversation as closed issues tend to get lost in the mix.
