### ISSUE TITLE
What are the event and message indexes used for?

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1306]
What are the message and event elasticsearch indexes used for and what would I do to cause a document to be written to those indexes? I am trying to migrate ES5 documents to ES7 and I want to make sure I can test it thoroughly. I tried to figure it out in the code but it isn't straightforward...

**Comment by mahalaxmiganesh** [comment]
message and event elasticsearch indexes are used in Event feature support.

With Event feature, being able to produce an event (message) to an external system like SQS or internal to Conductor.
1.	When using Conductor queues,  Events i.e messages are published into Conductor Queue, then these messages are indexed into Message index. 
2.	For Conductor to take any actions based on the Event. Event Handler will listen to Conductor queues and performs a list of actions. These event execution details are indexed into Event index

**Comment by rickfish** [comment]
That is what I thought but I cant seem to get these documents to be written to the indexes. I created an event handler, started a workflow with a wait task and then started a workflow with an event task to complete the task. Everything worked (both workflows completed) but I dont see anything in the event or message indexes). Also set breakpoints in the es dao where they would be written but the breakpoints did not hit.

**Comment by rickfish** [comment]
Never mind. It is working. For some reason, I had to wait for the SimpleEventProcessor.refresh() method to be invoked. Not sure why it wasn't. Thanks for your help!

**Comment by rickfish** [comment]
Strange...it worked once but after that I cant get SimpleEventProcessor.handle to be invoked. Is there some sort of setting for that??? Confused.

**Comment by kishorebanala** [comment]
@rickfish Ensure SimpleEventProcessor is bound as eagerSingleton in core module and that scheduled thread pools are initialized successfully at launch.
https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/config/CoreModule.java#L97

**Comment by mdepak** [comment]
@kishorebanala In the `SimpleEventProcessor`'s` handle()` method, all the event messages are indexed in elastic search. For our use case with large event loads, because of the IO involved in elastic search, the event processing becomes slow as the event queue polls are waiting for the handle to complete based on the Observable solution to backpressure problem. Since the event messages indexed in elastic search are not used anywhere what are the implications of disabling indexing only during indexes through a flag? 

Further, all other index operations allow async implementations expect 'addMessage()' method. Can it be made async to improve event processing performance?
