### ISSUE TITLE
Go Worker Implementation

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#131]
I have a go worker implementation for client/worker similar to the python client implementation that I would like to contribute to the project.  Would this be ok?

**Comment by v1r3n** [comment]
@cquon that will be great.  Do you mind sending a PR to `dev` branch?  Are you using channels and worker pools (https://gobyexample.com/worker-pools) ?

**Comment by cquon** [comment]
@v1r3n I am using workers but not channels.  Similar to how the python client specifies a thread count for each worker that will poll and execute, I am creating the specified number of goroutines (workers) to poll and execute as well.  One thing I wanted to inquire about was should the code be placed in Netflix/conductor/client/go ?  From what I have been reading most go applications are in their own repository and this seems like it would be embedded.  I have written an install / run script that can be run from the Netflix/conductor/client/go that utilizes the GOPATH to copy the files, install dependencies and run, but am not sure if this is the right approach.  Do you have any pointers/preferences on this?

**Comment by v1r3n** [comment]
@cquon 
Given we already have python client in the /conductor/client repo, I would suggest you keep go in the same.

I would suggest few things:

1. Use the `log` package in golang to do the logging as opposed to "fmt"
2. In the code, the URLs are relative to /api/*, make the /api also part of the constructor ```conductor.NewConductorHttpClient("http://localhost:8080/api")```. The reason is that /api is part of the deployment context and could be different based on how you deploy conductor.  
3. Move the code for the example tasks task_1_exec.go and task_2_exec.go into maybe a sample directory/package. 
4. The executeFunction() function should probably return the map[string]interface{} rather than a JSON string in the second parameter.  (https://github.com/cquon/conductor/blob/1eb5df1c1327cecba4b51bad3f02ccc59581147d/client/go/conductorworker.go#L38)  Do you think that is possible?  That will ensure worker implementation can just return a map of output and the client takes care of converting it to JSON correctly.
5.  The return for the executeFunction() function returns TaskStatus the possible return values for TaskStatus is not same as Task's Status as input.  You want to model these values as per https://github.com/Netflix/conductor/blob/dev/common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java#L31

@vikramsingh2104 for further comments.  Otherwise this looks good.

**Comment by cquon** [comment]
@v1r3n Thank you for the feedback.

I have made changes for 1,2,3 exactly as said as they were very straight forward.

For 4,5 I am now returning a TaskResult type defined:
(https://github.com/cquon/conductor/blob/24360d5f6f2bccf1c3b6593906d783d7bcf98def/client/go/task/taskresult.go)

Now all user task implementations will be functions that return this TaskResult, and in the Execute() function, based on the TaskResult, it will unmarshal it into JSON and send that as the body to update the task to the conductor server.

**Comment by v1r3n** [comment]
@cquon thank you.  Let me take a look.

**Comment by v1r3n** [comment]
@cquon It seems there is an external dependency on the http client that I missed.  Can you put that as part of the package?

**Comment by cquon** [comment]
@v1r3n Yes I will do so and resubmit a pull request.
