### ISSUE TITLE
Best practice : Cleanup of redis and elasticsearch database (and synchronization)

### ISSUE THREAD

**Issue by csperli** [Netflix/conductor#1315]
Hi all,

I'm searching for a best practice solution regarding cleanup and synchronization of Redis and ES databases.
We have configured conductor with db=dynomite.
Using dynomite cluster with 3 nodes and underlying redis db.

After a certain time of working with conductor, redis db is full.

- Configuring redis without eviction, we are facing some redis memory errors at this time, which then causes errors in conductor. (Which is clear)

- Configuring redis with eviction, the redis memory errors are gone. But eviction not only removes old workflows but also our custom workflow and task definitions. So again we are facing problems in conductor. At this scenario we also facing the problem of inconsistency between redis db and elasticsearch db. So the workflow in redis may be removed but they are still there in elasticsearch.

So my question is, is there any proposal how to solve this database problems ?
What is the best practice to do, when we see redis database is reaching its limit ?
How can we cleanup redis database and also get synchronization to elasticsearch database ?
Do we have to implement own cleanup strategy using the rest api /workflow/{workflowid}/remove with archiveWorkflow=false or are there any other proposals ?
Is there a possibilty to use redis eviction for that, without getting workflow defs removed and also synchonization with elasticsearch database ?

A lot of questions, I know.
I would be glad if someone could help us with these questions.

Thank you in advance

Chris

**Comment by manan164** [comment]
Hi @csperli . We are in same boat. I have asked this [question](https://github.com/Netflix/conductor/issues/1243) earlier.
1) For high throughput workflow we are using archive workflow true so it will be removed from redis on completion. 
2) We are using async indexing in ES with queue size 15k, which is also not sufficient during peak hours. And after the queue is full, we drop the indexes.  During non peak hours it is fine.

So potentially there are two issues,
1) Redis is getting piled up.
2) Workflow are not searchable from UI because it is getting dropped after queue is full.

We will not be able solve 1st problem without solving 2nd one otherwise till the workflow is in redis we will be able to search.
We are trying to solve the second problem in phases.
These are the approaches we have tried.
1) Introduce batch indexing while indexing into ES. It is mentioned in the PR:- https://github.com/Netflix/conductor/pull/1269. We saw much improvement with the batch size of 100. This number is not result of any hypothesis. You are free to use any.
2) Limit the number of fields that are being indexed. We did not see much improvement here.
3) Change the index prefix daily. Here also we did not see any much improvements. Also we have to tweak the retrieval logic in order to search workflow in ES.
4) Index only when status is terminal. This limit the indexing calls to 50% but this does not solve the actual problem.

The approach that we are trying currently is to publish to kafka and have another service which will consume from kafka and index to ES. We are in process to monitor the lag we have as rate of publishing to kafka will be much faster then the rate of consuming and putting into ES. This is mentioned in the PR:- https://github.com/Swiggy/conductor/pull/32.
Feel free to ask questions.
@naveenchlsn Please add your thoughts.

**Comment by naveenchlsn** [comment]
Index Dao and execution Dao are two separate concerns and should be scaled independently of each other. 

Since we are writing to both the Dao's one after other, in case we face an issue writing to indexing Dao but if execution Dao succeeds there is no way to recover from the fault and vice versa. 

Writing to Kafka provides a replay mechanism to handle this. So if a queue Dao is modelled on a persistent queue like Kafka, both execution Dao and indexing Dao can independently read and update the corresponding data stores. If one of them misbehaves we can replay the messages and recover.  @manan164
 
@apanicker-nflx @kishorebanala . Would this fit into the long term view of conductor as key value dao's such as dynamo and Cassandra are antipatterns to implement queues.  We can also remove index Dao from the critical path. 



For removing redis completed execution data, we can implement WorkflowStatusListener to call the remove API to delete the data. We have implemented the code for this. We will raise the PR this useful to others in the community as well. @csperli @kishorebanala @apanicker-nflx

**Comment by apanicker-nflx** [comment]
Considering a 2-part approach to remove Elasticsearch off the critical path and to relieve the pressure on ES:

1. Reduce indexing operations 
2. Asynchronous indexing

Index the workflow data only when a workflow is started and when a workflow enters terminal state. Index the task data only when the associated workflow enters terminal state. 

All indexing operations can be performed asynchronously using an executor service working off a LinkedBlockingQueue. Additionally, all task indexing operations can be performed in bulk using the `BulkRequestBuilder` while workflow indexing operations can be performed individually. This is to avoid workflow state getting overwritten in elasticsearch by a previous stale state for short-running workflows.

@csperli @manan164 @naveenchlsn 
Please let us know your thoughts on this approach.

**Comment by manan164** [comment]
> Hi @csperli . We are in same boat. I have asked this [question](https://github.com/Netflix/conductor/issues/1243) earlier.
> 
> 1. For high throughput workflow we are using archive workflow true so it will be removed from redis on completion.
> 2. We are using async indexing in ES with queue size 15k, which is also not sufficient during peak hours. And after the queue is full, we drop the indexes.  During non peak hours it is fine.
> 
> So potentially there are two issues,
> 
> 1. Redis is getting piled up.
> 2. Workflow are not searchable from UI because it is getting dropped after queue is full.
> 
> We will not be able solve 1st problem without solving 2nd one otherwise till the workflow is in redis we will be able to search.
> We are trying to solve the second problem in phases.
> These are the approaches we have tried.
> 
> 1. Introduce **batch indexing** while indexing into ES. It is mentioned in the PR:- #1269. We saw much improvement with the batch size of 100. This number is not result of any hypothesis. You are free to use any.
> 2. **Limit** the number of fields that are being indexed. We did not see much improvement here.
> 3. Change the **index prefix** daily. Here also we did not see any much improvements. Also we have to tweak the retrieval logic in order to search workflow in ES.
> 4. Index only when status is **terminal**. This limit the indexing calls to 50% but this does not solve the actual problem.
> 
> The approach that we are trying currently is to publish to kafka and have another service which will consume from kafka and index to ES. We are in process to monitor the lag we have as rate of publishing to kafka will be much faster then the rate of consuming and putting into ES. This is mentioned in the PR:- [Swiggy#32](https://github.com/Swiggy/conductor/pull/32).
> Feel free to ask questions.
> @naveenchlsn Please add your thoughts.

Hi @apanicker-nflx , I was referring the same thing in point 4.
Also, one thing to mention, we are using async indexing. Still, we see that in high throughput scenario most of the indexing request will be dropped because queue size will be maximum. That was the reason we came up with the bulk indexing approach. We saw some improvements there.
Still, we are working on kafka bypassing and have another service just to consume from kafka and write to ES.

One question, Do we really need to separate out the task indexing with the workflow indexing operations? Shouldn't the LinkedBlockingQueue will guarantee ordering? Or is it because of distributed architecture?

**Comment by apanicker-nflx** [comment]
Hi @manan164 , thanks for the response.

> Still, we see that in high throughput scenario most of the indexing request will be dropped because queue size will be maximum.

I believe that reducing the number of indexing operations by only indexing at workflow start/end can help with this. I am suggesting a slight change to your point 4, such that we index twice for a given workflow so that RUNNING workflows are searchable in the UI.

> Do we really need to separate out the task indexing with the workflow indexing operations? Shouldn't the LinkedBlockingQueue will guarantee ordering? Or is it because of distributed architecture?

Yes, as you pointed out, the concern here is with the distributed architecture that a workflow can start on one node (indexed in RUNNING status) and it can move to a terminal state on another node. My primary concern is that buffering indexing operations for workflow twice (1. Async and 2. Bulk) would lead to inconsistent state being indexed. Since task data is indexed only once, task indexing would not see any inconsistency.

Thoughts?

**Comment by manan164** [comment]
Hi, @apanicker-nflx Thanks for the clarification. 
I would say, even if we index when we create the workflow so that we will be able to search RUNNING workflows, but that wouldn't make much sense because in high throughput scenario we generally archive the workflow the moment it is complete. Otherwise, Redis will be full in no time. Also, the time, when it started to reach to terminal state, is very less generally in terms of 200~300 ms
The actual problem is we are not able to search the workflow even after some time because its indexing request is dropped in [bounded queue](https://github.com/Netflix/conductor/blob/master/es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchRestDAOV5.java#L133). Of course, we should avoid inconsistent state while indexing but we will not be able to know it as the rpm is very high.  Also, there is no way we can find out that the conductor is being used in a high throughput scenario. I 
While looking at the [WorkflowStatus](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/run/Workflow.java#L38) Except RUNNING only PAUSED is nonterminal. And we won't be saving much here because most of the workflows will reach terminal state immediately after getting started.
I have pointed out the same thing in https://github.com/Netflix/conductor/issues/1243#issuecomment-535184226.
We need one consumer service which consumes from kafka. Now here I am asking is how do you want me to write the new indexDAO. Please go throught the latest comment on that.

**Comment by apanicker-nflx** [comment]
@manan164 
> wouldn't make much sense because in high throughput scenario we generally archive the workflow the moment it is complete. Otherwise, Redis will be full in no time. Also, the time, when it started to reach to terminal state, is very less generally in terms of 200~300 ms

This is not true in most cases. Most of our users run workflows which run for a few minutes to few hours. There are also a few use-cases where workflows can run over a period of a few days. In these cases, users still expect to search for workflows based on input data. 
I have pushed a change with the above-mentioned suggestion, please take a look - https://github.com/Netflix/conductor/pull/1333. I will release a beta version with this change to test out internally.

> The actual problem is we are not able to search the workflow even after some time because its indexing request is dropped in bounded queue. I have pointed out the same thing in #1243 .We need one consumer service which consumes from kafka. Now here I am asking is how do you want me to write the new indexDAO. Please go throught the latest comment on that.

I understand your concerns here regarding dropping messages at high throughput. Will re-open the thread and continue discussion there.

**Comment by playmakerAnup** [comment]
@manan164  @apanicker-nflx 
Guys any success??? 
Can we set a TTL for the redis keys to purge the workflow executions after a certain period OR re-indexing to get better search results and removing them is a better option.

**Comment by manan164** [comment]
Hi @playmakerAnup  
1) For ES Currently, we are doing Kafka indexing and have separate consumer service to consume from Kafka and index to ES. Let me know if you need more details. I have raised the test [PR](https://github.com/Netflix/conductor/pull/1337) on this.
2) For Redis cleanup, We can't have a working mechanism of ttl because internally redis-keys are set. Conductor make set based on the task and workflow and store the id of the instance running. If we remove set it can spoil the current execution. Task and workflow will be stuck. Also we cant set tttl on the set member. [issue](https://github.com/antirez/redis/issues/1042). We remove workflow based on [status listener](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java#L80). We have customized the implementation and remove a workflow from redis the moment it reaches terminal state.
Let me know your views.

**Comment by playmakerAnup** [comment]
thanks @manan164 for the quick response, 
 how about re-indexing ES externally/manually(localhost:9200/_reindex) and once the result for Search API is clean, I can use remove API to remove them.
