### ISSUE TITLE
[Question] Current support for cassandra persistence module

### ISSUE THREAD

**Issue by cshen200** [Netflix/conductor#1376]
Hi there, 

This might be somewhat related or a continuation of issue #819. We're looking to use/extend cassandra db option as our execution data layer. It looks like there're quite a few methods in ExecutionDAO that the cassandra impl didn't implement. I understand that the cassandra module is only providing partial implementation, what I want to find out is that what functionally are we missing(or considered not critical) from using/running conductor with the cassandra impl as is?

Is there planned support for cassandra now or in the near future?

Thanks in advance,
Chao

**Comment by smullins3000** [comment]
+1

**Comment by kishorebanala** [comment]
@cshen200 As @apanicker-nflx mentioned in the other thread, at the moment, Cassandra module supports ExecutionDAO persistence. We're planning to add MetadataDAO persistence sooner. We're not sure about adding QueueDAO implementation though. We've been using Cassandra in production for the past year at Netflix and definitely plan to support it.

**Comment by cshen200** [comment]
Thanks for the response @kishorebanala! 

So if I'm understanding this correctly, the current Cassandra module which implemented some functionality of ExecutionDAO persistence(Looking at code in master branch) is sufficient enough to support your production needs? 
And that the other unimplemented methods are not used in Prod workflow execution?

I'm curious what your setup is in Production, do you use Cassandra as your backing DB for execution data while using different DB(s) for other DAOs?

Thanks.
Chao

**Comment by apanicker-nflx** [comment]
@cshen200 
>So if I'm understanding this correctly, the current Cassandra module which implemented some functionality of ExecutionDAO persistence(Looking at code in master branch) is sufficient enough to support your production needs? And that the other unimplemented methods are not used in Prod workflow execution?
This is correct. Current implementations are sufficient enough to support workflow execution requirements.

>I'm curious what your setup is in Production, do you use Cassandra as your backing DB for execution data while using different DB(s) for other DAOs?
In production, we are using Cassandra for storing all the workflow and task execution data. We are using dynomite/dyno-queues for the metadata DAO and the queue DAO respectively. We plan to migrate the metadata DAO to Cassandra and we will be implementing this in Conductor soon. 

As for other methods in the execution DAO, all of the methods are providing a search functionality and do not impact workflow/task execution, and we are utilizing the indexDAO to surface this information to the APIs. 
For the methods related to event execution, we are continuing to use dynomite for this purpose. These will also be implemented in Cassandra soon.

However, if you choose to use Cassandra as your execution store, you would still need to use another dependency for your queueDAO implementation, since we do not plan to support/implement a queueing layer built on top of Cassandra.

**Comment by cshen200** [comment]
Thanks much for the detailed information @apanicker-nflx, really appreciate it! That answers all my questions above.

We'll move forward with using redis for our execution and queue backing DB, while using aurora as our metadata DB.

While I've got your attention, a couple more questions if you don't mind. 

1. I'm sure you've considered this, but any concern on the volatile nature of using in-mem cache to serve metadata? Curious what your redundancy level is for your dynomite clusters for metadata?

2. Is the additional wire up and setup for supporting different DB for different data types(as mentioned above) checked in to this repo? 

Thanks again,
Chao

**Comment by apanicker-nflx** [comment]
> 1. I'm sure you've considered this, but any concern on the volatile nature of using in-mem cache to serve metadata? Curious what your redundancy level is for your dynomite clusters for metadata?

Our dynomite cluster is set up with cross-region replication with in-region replication factor of 3. Additionally, the in-memory redis data is persisted to disk every few minutes and a snapshot of the data is taken every day. Since the metadata (workflow and task definitions) do not change frequently, this setup has been working fine for our use-case.

> 2. Is the additional wire up and setup for supporting different DB for different data types(as mentioned above) checked in to this repo?

It is not checked in, since this is a very specific setup for our internal deployment, which was born out of live migration from dynomite to C*. The additional wire-up is a very thin layer similar to the [ExecutionDAOFacade](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java) but implements the ExecutionDAO interface. This implementation is a simple orchestrator of the respective apis to the corresponding DAO layers (C*, dynomite, index).
