### ISSUE TITLE
204 response when creating task definition 

### ISSUE THREAD

**Issue by amoolya19** [Netflix/conductor#138]
Hi,
I am trying to register the task for the testing purpose and i am getting 204 as response. below is the task trying to send to http://localhost:8080/api/metadata/taskdefs
[{
    "name": "test_task1",
    "description": "test_task1",
    "retryCount": 0,
    "timeoutSeconds": 0,
    "inputKeys": [
      "param1"
    ],
    "outputKeys": [
      "param2"
    ],
    "timeoutPolicy": "TIME_OUT_WF",
    "retryLogic": "FIXED",
    "retryDelaySeconds": 600,
    "responseTimeoutSeconds": 600
  }]
request headers are : 
Content-Type: application/json
Content-Length: 337

when i checked the conductor UI under metadata/task, my task is not present. i assume it has to be present. Let me know if am doing anything wrong.

**Comment by amoolya19** [comment]
sorry.. i have task def in the UI though 204 is showing. i have 1 more gap here. what are inputkeys, input template in task def and input parameters in wf def? what is the link among these 3 ? could you provide me any example (step by Step) so that it would help me to understand better.

**Comment by v1r3n** [comment]
inputKeys in task definition and input parameters in workflow definition are used for documenting the required inputs for both task and workflow.  These values are not validated or used at runtime otherwise.  

inputTemplate is used to support some older workflows for backward compatibility - I would not use it as we might remove it in future versions.
