### ISSUE TITLE
Redis cluster mode broken as of PR #1369

### ISSUE THREAD

**Issue by orogvany** [Netflix/conductor#1431]
Redis cluster mode broke on update of jedis (PR #1369)

Would only get `Caused by: redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 10262 10.xxx.xxx.xxx:6379`

Per https://github.com/xetorthio/jedis/issues/1255 the JedisPool is not sufficient to work with a cluster, need to use the JedisCluster.

Conductor introduced its own JedisCluster to implement JedisCommands rather than JedisClusterCommands, but this does not seem to honor any clustering, so the above exception is thrown

The PR #1422 does fix this issue, but the proposer closed the PR, as they tried to then use https://github.com/mdepak/conductor/commit/4cb0a7bf28bb7710733de35c8b69d0e32c31f687 as a cleaner solution.  Unfortunately, I don't think this is the right solution, as ShardedJedis has the following limitation `ShardedJedis create shards logically, so it doesn't support H/A (failover), and re-distribute keys (because key distribution is based on algorithm and we can't change on the fly).` . It also didn't seem to work right as, if I'm understanding correctly, shardedJedis does need to be provided all the shards up front, rather than discovering them (at least on Elasticache)

The proposed #1422 does fix the issue though, and probably should be adopted or another fix put in place to allow cluster mode with redis to function.

Note: possibly a similar fix would be required for sentinal redis, but as I don't have a configuration that uses sentinal, I'm not positive if it would need the conductor JedisCluster, or the JedisClusterMod fix to function.

**Comment by mdepak** [comment]
@orogvany Using `JedisCluster` client addresses the issue with the Redis cluster and it is verified. I will send PR to dev with the changes shortly.

**Comment by orogvany** [comment]
Thanks @mdepak . Yes I noticed your PR using JedisCluster fixes the issues, and we verified in our instance.  It's a pity the ShardedJedis solution you tried did not work, it's much cleaner, but your JedisClusterMod fix (or similiar) works great.

Thanks!

**Comment by apanicker-nflx** [comment]
@orogvany Thanks for flagging this. `JedisClusterCommands` could not be used because jedis-3.0 changed the interface such that it does not extend from `JedisCommands` as in jedis-2.x.
The `RedisQueues` constructor in dyno-queues requires `JedisCommands` for instantiation however. Hence, this forced the usage of `JedisCluster` which implements `JedisCommands`.

Also, we confirmed with a RedisSentinel configuration user and they confirmed that this was working for them. ([See here](https://github.com/Netflix/conductor/pull/1369#issuecomment-548434965)).

@mdepak Please send us a PR with the fix and we will review/merge this soon.
