### ISSUE TITLE
Updating long running tasks

### ISSUE THREAD

**Issue by markusa380** [Netflix/conductor#1455]
This is kind of related to issue #71.

I have a service that is running a task which might take minutes or even hours to complete.
In this case, sending an update to Conductor is crucial in combination with the `responseTimeoutSeconds` to make sure that the worker is actually still running and did not die for some reason.

The difference from the issue mentioned above is that the long running work happens directly on the worker, which means that only this one instance of my service knows about the tasks state. I know that Conductor is designed for small tasks, but in this case I don't really have a choice. Writing a second service just to poll the state from the actual service seems highly redundant.

Here is the expected behaviour:

- When a task is not updated at least every X seconds, it should time out (-> `responseTimeoutSeconds` ?)
- When a task is not complete after X seconds, it should fail (-> `timeoutSeconds`)
- When a task is updated it will not be put back into the queue, but will continue being `IN_PROGRESS` with the two behaviours above (especially that a task times out if it isn't updated continously).

Some questions I have:

- How should one approach this?
- Should `callbackAfterSeconds` be set to `0`, `-1`, `null` or even the same as `timeoutSeconds` to avoid polling from a different worker?
- What value should `responseTimeoutSeconds` have? Does it even work when updating multiple times in a row?

Thank you for the explanation.

**Comment by apanicker-nflx** [comment]
@MarkusA380 

> - When a task is updated it will not be put back into the queue, but will continue being IN_PROGRESS with the two behaviours above (especially that a task times out if it isn't updated continously).

Seems the pattern you are looking for here is that of a heartbeat mechanism from the worker that is currently processing the task. Currently, conductor does not support this.

> - Should callbackAfterSeconds be set to 0, -1, null or even the same as timeoutSeconds to avoid polling from a different worker?
> - What value should responseTimeoutSeconds have? Does it even work when updating multiple times in a row?

Updating a task within responseTimeoutSeconds with IN_PROGRESS status does not guarantee that the same worker instance will pick up the task from the queue. Setting a value for `callbackAfterSeconds` during such an update ensures that the task is only available to be polled again after this time value has expired and will stay in the queue (similar to an invisibility timeout). This mechanism can be used to poll and update the task multiple times in a row. However, these polls and updates could happen across different worker instances which does not seem to fit your need.

> How should one approach this?

In order to solve this use case, I would recommend you to consider using a [WAIT](https://netflix.github.io/conductor/configuration/systask/#wait) task in your workflow. So, your task which invokes processing would basically be a fire-and-forget task such that the worker starts the processing and updates Conductor with COMPLETED status once processing is kicked off successfully. The WAIT task could follow this task and you could add logic in your service to fire an event once the processing complete. You can also configure a timeout for your WAIT task such that if the event is not received within this time, the processing is considered to have failed.

**Comment by SwarnadeepC0** [comment]
Did the solution work?
