### ISSUE TITLE
No expiration time/retention period configuration option for Elasticsearch and Redis

### ISSUE THREAD

**Issue by RemcoBuddelmeijer** [Netflix/conductor#1503]
There is no possibility to set a retention period/expiration time for the task and workflow metadata in both Redis and Elasticsearch.
With this, you manually have to delete keys and documents from both the services.
Please add the possibility to automatically let documents and indexes be removed by the respected service.

**Comment by apanicker-nflx** [comment]
@RemcoBuddelmeijer We found that automatic deletion of workflow and task execution data based on a TTL does not fit our needs. This is because workflows/tasks could be in progress for an arbitrary period ranging from seconds to months. Setting a fixed TTL in this case would negatively impact the system if active workflows/tasks were to be deleted. The [IndexDAO exposes a method](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/dao/IndexDAO.java#L175) which allows the user to identify archivable workflows and this could be used to perform deletion/cold storage archival as per user requirements.
