### ISSUE TITLE
Do-while task should be created first as Worker task?

### ISSUE THREAD

**Issue by leissen** [Netflix/conductor#1559]
I just want to run a simple workflow including a do-while task as shown below. But I met the following error when submitting a workflow job. But if I register a simple worker task named "loop_task" and try to invoke job again, the error will disappear. I think do-while task is a system task and I needn't register a DO_WHILE task. Is it right? Thanks. 

[INFO ] 2020-03-03 15:28:10,723 WorkflowExecutor - Execution terminated of workflow: 64d7849c-6947-4c34-bee2-a6508c2b6606
com.netflix.conductor.core.execution.TerminateWorkflowException: Invalid task specified. Cannot find task by name loop_task in the task definitions
	at com.netflix.conductor.core.execution.mapper.DoWhileTaskMapper.lambda$null$0(DoWhileTaskMapper.java:81)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.netflix.conductor.core.execution.mapper.DoWhileTaskMapper.lambda$getMappedTasks$1(DoWhileTaskMapper.java:79)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.netflix.conductor.core.execution.mapper.DoWhileTaskMapper.getMappedTasks(DoWhileTaskMapper.java:78)
	at com.netflix.conductor.core.execution.DeciderService.getTasksToBeScheduled(DeciderService.java:645)
	at com.netflix.conductor.core.execution.DeciderService.getTasksToBeScheduled(DeciderService.java:608)
	at com.netflix.conductor.core.execution.DeciderService.startWorkflow(DeciderService.java:265)
	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:107)

My workflow definition Json:
{
  "name": "workflow1",
  "description": "",
  "ownerEmail":"admin@163.com",
  "version": 1,
  "tasks": [
    {
      "name": "loop_task",
      "taskReferenceName": "LoopTask",
      "type": "DO_WHILE",
      "inputParameters": {
        "value": "${workflow.input.value}"
      },
      "loopCondition": "if ($.LoopTask['iteration'] < $.value) { true; } else { false; }",
      "loopOver": [
        {
          "name": "task1",
          "taskReferenceName": "while_task1",
          "type": "SIMPLE"
        }
      ],
      "startDelay": 0,
      "optional": false
    },
    {
      "name": "task2",
      "taskReferenceName": "task2",
      "type": "SIMPLE"
    }  ]
}

My workflow job invoking Json:
{
  "name": "workflow1",
  "version": 1,
  "correlationId": "workflow1_job1",
  "input": {
    "value" : 3
  }
}

**Comment by manan164** [comment]
Hi, @leissen , Thanks for bringing this up. We need to register loop_task in this case even if it is a system task. This is an exceptional case. Since ```DO_WHILE ``` task can be scheduled multiple times we have to check that it is not being scheduled if it is in terminal state.
YOu facing issue because of [this](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/mapper/DoWhileTaskMapper.java#L68). 
Just few note,
1. Currently in a workflow do not have any more task. Do_While task should be last in workflow. I have raised [PR](https://github.com/Netflix/conductor/pull/1479) for this.
2. Subworkflow inside Do_While task is not supported. I have raised [PR](https://github.com/Netflix/conductor/pull/1435) which is work in progress.
Thanks for trying. Let me know feedback.
I would suggest please pull 1st Pr branch and try. I have made few optimizations there.

**Comment by leissen** [comment]
Hi, @manan164 , thank you very much for the quick reply.  I will take a look at this PR https://github.com/Netflix/conductor/pull/1479. So currently the DO_WHILE task must be the last task in a workflow, right? I meet another issue described in https://github.com/Netflix/conductor/issues/1558.
Could you help to take a look? Thanks again.

**Comment by apanicker-nflx** [comment]
Closing since #1479 is merged.
