### ISSUE TITLE
WorkflowExecutor hard to extend

### ISSUE THREAD

**Issue by andrea11** [Netflix/conductor#1580]
Hello all,
We have an application using conductor core to orchestrate workflow. For business purpose, we had to extend the Conductor to add new property (we already created a [PR](https://github.com/Netflix/conductor/pull/1336) to make conductor model more extensible, if you could also some feedback on that). Currently, we need to setup some fields of the workflow before to start it (because it will be decided before to allow us to add these fields, and in case of sub-workflow as first task, the behaviour of our workflow will break. For more info cf. https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L398)
Now, we were thinking to create an interface to be implemented in the WorkflowExecutor, with a startWorkflow that does not take all these parameters, but only the workflow execution to start. Meanwhile, the creation of this workflow execution will happen in another method (protected one).

A simple snippet:
```java
public String startWorkflow(final Workflow workflow)

protected Workflow buildWorkflow(
    WorkflowDef workflowDefinition,
    Map<String, Object> workflowInput,
    String externalInputPayloadStoragePath,
    String correlationId,
    Integer priority,
    String parentWorkflowId,
    String parentWorkflowTaskId,
    String event,
    Map<String, String> taskToDomain)
```

What do you think? Would you agree with this approach?

Thanks

**Comment by apanicker-nflx** [comment]
@andrea11 I did leave a comment on #1336 that since this breaks interface contracts, we would want to hold off on making this change in a minor version upgrade but will definitely add this to our list of features for the next major version upgrade.

Your approach for introducing an interface for the start workflow would work, but please ensure that validations are being applied in the `buildWorkflow` method.
