### ISSUE TITLE
Deploy conductor server in a distributed way？

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1581]
In production environment, does conductor server support multi instance deployment？If yes, how to deploy conductor server in a distributed way, and Is there a deployment instruction document？

**Comment by apanicker-nflx** [comment]
@andyyumiao Yes conductor server can be deployed across multiple instances. We do not have an instruction document for this yet, but basically the deployment would just mean booting the server jar across multiple instances and using external databases(instead of in-memory) and elasticsearch deployments(for UI/index/search purposes).
