### ISSUE TITLE
how to use redis instead of dynomite?

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1582]
how to make the configrations?

**Comment by andyyumiao** [comment]
we have an own redis cluster, and want to use it as the storage for conductor without dynomite, is that ok?

**Comment by apanicker-nflx** [comment]
Yes, you should be able to use redis cluster as the persistence layer for your conductor deployment instead of dynomite. Please ensure to wire up the [correct instance of the jedis provider](https://github.com/Netflix/conductor/tree/master/redis-persistence/src/main/java/com/netflix/conductor/jedis) for what suits your configuration.
