### ISSUE TITLE
Terminate workflow by correlationId

### ISSUE THREAD

**Issue by manan164** [Netflix/conductor#1597]
Hi all,
We have several use cases like we start the workflow with some correlation Id. We don't store the workflow Ids. They are independent workflows. On certain events, we are terminating by correlationId we have used to start a workflow. We have common logic to form correlationId so we don't need to store that also.
Will it be a useful contribution?
@apanicker-nflx @kishorebanala

**Comment by apanicker-nflx** [comment]
@manan164 Given that this API - ```GET /workflow/running/{name}/correlated/{correlationId}?includeClosed=true|false&includeTasks=true|false``` exists, you should be able to get the list of all workflows for a given correlation id. You can then iterate on this list to terminate the workflows or use the bulk api to terminate all of these workflows.

**Comment by techyragu** [comment]
@apanicker-nflx

**Comment by apanicker-nflx** [comment]
@techyragu Since the correlationId is an indexed field, you could use the ```GET
/workflow/search``` API to search for all workflows given just the correlation id. You could combine the query for correlationId with the status to further filter the search.

There is no bulk delete API currently supported, but we would welcome a PR for the same :)

**Comment by techyragu** [comment]
@apanicker-nflx
To begin with I tried with existing bulk api to terminate WFs, but it did not seem to work.
Do you have any working example for existing WF API
