### ISSUE TITLE
Conductor for B2B and Enterprise level Solution

### ISSUE THREAD

**Issue by maxygo** [Netflix/conductor#1604]
Hi All,

I'm looking over the Netflix Conductor in order to use it as microservices orchestrator for various business cases. It looks pretty what is needed, but would like to check some things. I already walked through the doc and some github issues/question so many questions were resolved, but still some of them there which would be great to check with you:

1. Metrics/Logs Visualization: there is elasticsearch which as far as I got gathering workflows/tasks states changes and events. Is there any Kibana build outofthebox in Conductor which allows to watch over those details? Please advice.
2. Can elasticsearch be replaced with another tool like Scalyr for example? Could you please let me know what is required to do in order to switch it? If it requires code changes of conductor itself or matter of configs?
3. I assume with docker configs it is possible also to convert and create Kubernetes manifest files and run Conductor and it's throd parties as kubs cluster. Does it require any additional configurations or setups to do in order run cluster which will be able to process 100m workflows a day? 
4. Regarding Zookeepr, is it enough just switch it on in configs. What is expected to be add in connections property? The link is broken in the doc to check some technical details.
5.  Is it possible to use RabbitMQ as external events provider for the Conductor? In the doc it mentioned SQS, but I assume it is possible to use any MQ? If yes, does it require any conductor server code changes or matter of config?
6. HADR capability, as far as I got it is achieved with Dynomite and cluster scalability and the possibility to automatically store dumps on S3 or other cloud storage. Is that the right assumption?
7. Security: is there security support - authorization / authentication / encryption etc? Did not get from doc if there are some abilities with security. Please advice.
8. "Also there was a comment "The task execution is generally asynchronous but it can be enforced to run synchronously" - I found it in some blog article about conductor. So I wonder if it is mean with System tasks which looks like is executing in sync, but generally, it is the pure async solution to run worker tasks etc?
9. Distribution Execution Capability - if my kub cluster of Netflix will grow due to number of workflows to be executed (100k concurrently), so when it is scaled does it allow existing running workflows to start task execution on the new Conductor pods running or it will be running on the same instance where it was initiated? Maybe I missing something by explaining the topic, please let me know.
10. Finally, just thinking about the most critical point in the Conductor architecture - looks like it is Dynomite - if it down, then workflows are not executing and failing. So, something like single point of failure. But once it will be resurrected back - will conductor resume the workflow processing from the last stage where it was? Will it rerun tasks which stuck in progress or failed. Or how it will work, please provide some inputs on this.

Really appreciate your help and asnwers Team. **Thanks!**
Sorry in case some points are obvious or not clear.

**Comment by kishorebanala** [comment]
@maxygo Thanks for considering Conductor for your use case. 

> 1. Metrics/Logs Visualization: there is elasticsearch which as far as I got gathering workflows/tasks states changes and events. Is there any Kibana build outofthebox in Conductor which allows to watch over those details? Please advice.

We have ES5.x Kibana templates which we haven't published, but would be glad to do so. Also, we publish several metrics, which you can configure and visualize with tools like Atlas, Prometheus etc. Check this for more details: https://netflix.github.io/conductor/metrics/server/#publishing-metrics

> 2. Can elasticsearch be replaced with another tool like Scalyr for example? Could you please let me know what is required to do in order to switch it? If it requires code changes of conductor itself or matter of configs?

Indexing is optional and is extensible. However, you'd have to plugin your own module, say that implements Scalyr, similar to `es5-persistence` module in Conductor, which you can then configure in your conductor server set-up. You can similarly extend Conductor by plugging in your implementations for these interfaces: https://netflix.github.io/conductor/extend/#backend

> 3. I assume with docker configs it is possible also to convert and create Kubernetes manifest files and run Conductor and it's throd parties as kubs cluster. Does it require any additional configurations or setups to do in order run cluster which will be able to process 100m workflows a day?

Conductor is horizontally scalable. There are folks who have run it on Kubernetes (Gitter channel would be the good place to check about it), and you should be able to process 100M workflows with some minimal tuning of provided knobs.

> 4. Regarding Zookeepr, is it enough just switch it on in configs. What is expected to be add in connections property? The link is broken in the doc to check some technical details.

Zookeeper module is enabled by default. Take into consideration Zookeeper's scalablity, if you're planning to run Conductor at high scale. Also, consider redis-lock module for locking.

> 5. Is it possible to use RabbitMQ as external events provider for the Conductor? In the doc it mentioned SQS, but I assume it is possible to use any MQ? If yes, does it require any conductor server code changes or matter of config?

Yes, Someone just contributed AMQP bindings. You should be able to do the same with RabbitMQ. We don't have RabbitMQ bindings though.

> 6. HADR capability, as far as I got it is achieved with Dynomite and cluster scalability and the possibility to automatically store dumps on S3 or other cloud storage. Is that the right assumption?

There are several ways to achieve this. Conductor doesn't advocate one over the other and provides a generic solution which you can use to achieve your needs. For eg., Conductor can be set-up cross region with persistence layers that supports it, and achieve HADR

> 7. Security: is there security support - authorization / authentication / encryption etc? Did not get from doc if there are some abilities with security. Please advice.

AuthN and AuthZ is lacking in Conductor 2.0, and is one of the major features we'd like to work on for Conductor 3.0. We don't have an ETA yet for this. 

> 8. "Also there was a comment "The task execution is generally asynchronous but it can be enforced to run synchronously" - I found it in some blog article about conductor. So I wonder if it is mean with System tasks which looks like is executing in sync, but generally, it is the pure async solution to run worker tasks etc?

Correct. Worker tasks would go through Task lifecycle which involves pushing tasks to queues, polling for and executing the task, which is asynchronous. However, system tasks can skip "pushing to queue" part and can be executed immediately, which is as synchronous as it can get.

> 9. Distribution Execution Capability - if my kub cluster of Netflix will grow due to number of workflows to be executed (100k concurrently), so when it is scaled does it allow existing running workflows to start task execution on the new Conductor pods running or it will be running on the same instance where it was initiated? Maybe I missing something by explaining the topic, please let me know.

Conductor is stateless about workflow execution. This helps to easily scale down or scale up the Conductor cluster. Each node in the cluster works independently and hence the need for global distributed lock to avoid race condition between two nodes trying to evaluate same workflow.

> 10. Finally, just thinking about the most critical point in the Conductor architecture - looks like it is Dynomite - if it down, then workflows are not executing and failing. So, something like single point of failure. But once it will be resurrected back - will conductor resume the workflow processing from the last stage where it was? Will it rerun tasks which stuck in progress or failed. Or how it will work, please provide some inputs on this.

Apart from Dynomite, Conductor also supports MySQL, Cassandra and few other databases. And if the persistence layer is down or transiently unavailable, the workflows will be terminated with a handled exception. However, we're working on a solution to recover the workflow from persistence failures, and keep it running, so that when the persistence layer resumes, the workflows can continue processing from where it left.

Also, when you mentioned 100M workflow execution, we're curious about the frequency. Can you provide us estimates about the volume and variety of your workflow executions per day. 

Feel free to reach out with further questions or comments.

**Comment by maxygo** [comment]
@kishorebanala Thanks a lot for the inputs. It was really helpful.

> Also, when you mentioned 100M workflow execution, we're curious about the frequency. Can you provide us estimates about the volume and variety of your workflow executions per day.

There are not much details so far about this, we expect to have a different kind of workflows (not yet designed) which will involve parallel tasks execution (fork, join, exclusive join), conditional paths, subworkflows (it looks like a good solution to reuse similar workflow in more complex workflows), event handling. 
As for the volume, it might be the case that the conductor should process up to 1-2 billion of workflows during a month. Most of the workflows would be able to process for 1-5 mins, and some of them might take several hours.

I also have some other few inputs:
1. You mentioned that the scalability of the conductor allows processing 100m during a day. Any suggestions/advice in the needed powers?
2. Use Case: workflow has the following tasks Simple Task 1 -> Simple Task 2 -> and next parallel execution with 1 Simple task and some task which should be executed only on some Customer Acceptance first; once Customer accepts we should trigger the next task to be executed. How this can be achievable? I assumed it might be dynamic workflows and event handling, but maybe you can suggest some better solution?
3. Dynomite is suggested for HA as per configs. Also, there is a possibility to dump workflows and tasks definitions right (to S3)? If so, there is also some mechanism to restore dump in case of need and distribute through the cluster?  If you will have a chance, could you please share the docs on it or suggestion to consider?
4. when you said conductor has few persistent solutions (MySQL, Cassandra). Does it mean that Conductor will not use Dynomite and instead will store all workflows and tasks definitions, statuses within the MySQL/Cassandra? So, how in that case Conductor Queue will work? Does it still involve dynomite / redis? Not sure I see clear vision on this.

Thank you also for gitter suggestion, I will check it and check some details here as well.

**Comment by kishorebanala** [comment]
@maxygo No worries, glad to help!

> 1. You mentioned that the scalability of the conductor allows processing 100m during a day. Any suggestions/advice in the needed powers?

Well, we only load tested to the extend of processing around 10M workflows a day. While it is possible to scale Conductor to 100M workflows, I'd advise to invest into a load testing with synthetic data first and verify your use case. It might also help uncover potential bottlenecks at higher scale for your use case.

> 2. Use Case: workflow has the following tasks Simple Task 1 -> Simple Task 2 -> and next parallel execution with 1 Simple task and some task which should be executed only on some Customer Acceptance first; once Customer accepts we should trigger the next task to be executed. How this can be achievable? I assumed it might be dynamic workflows and event handling, but maybe you can suggest some better solution?

Yes, you can use event handler to complete a task. Other option is to periodically execute the same task by updating task with IN_PROGRESS state and reasonable `callBackAfterSeconds`.

> 3. Dynomite is suggested for HA as per configs. Also, there is a possibility to dump workflows and tasks definitions right (to S3)? If so, there is also some mechanism to restore dump in case of need and distribute through the cluster? If you will have a chance, could you please share the docs on it or suggestion to consider?

[Dynomite](https://github.com/Netflix/dynomite) is maintained by a separate team at Netflix, and they can better answer this question in their support channel.

> 4. When you said conductor has few persistent solutions (MySQL, Cassandra). Does it mean that Conductor will not use Dynomite and instead will store all workflows and tasks definitions, statuses within the MySQL/Cassandra? So, how in that case Conductor Queue will work? Does it still involve dynomite / redis? Not sure I see clear vision on this.

It is possible to use different databases for Queues and Workflow/Task persistence. Eg: You can use Dyno-queues for queues, and MySQL for persistence. This can be configured by plugging in the core interfaces I referenced above to one of the implementations in Conductor server.

Feel free to ask if you have further questions / comments.
