### ISSUE TITLE
How to implement long running approval tasks?

### ISSUE THREAD

**Issue by mcancio** [Netflix/conductor#1606]
Hi team, good day. I'm looking to design a four-eyes principle (user review/ approval) workflow using Conductor. User submits a request which triggers the approval workflow.

What I have tried so far:
1. Workflow using simple tasks :
task1(SIMPLE) - email approvers
task2(SIMPLE) - get approval
task3(DECISION) - decide using task2.output.is_approved.
task4(SIMPLE) - if approved, process request.

task2 - get approval - updates some kind of table in the backend with the taskId and workflowInstanceId. It will stay in progress until approval clicks on the "approval link". 
Approval link calls a script which completes the task (using taskId and workflowInstanceId). 

Problem: task2 remains in progress for weeks. When I poll this task, I keep on getting the same task repeatedly and this would cause unnecessary duplicate calls on our system. 
Is there a way to just lock the task to a worker, and not allow any other worker to get the same taskId?

2. Workflow using wait and event tasks :
Main workflow:
task1(SIMPLE) - email approvers
task2(WAIT) - wait for approval
task3(DECISION) - decide using task2.output.is_approved.
task4(SIMPLE) - if approved, process request.
Approve workflow:
task1(SIMPLE) - get approval decision (from workflow.input.is_approved)
task2(EVENT) - complete wait for approval event (Main Workflow task2)

Problem: with this approach, the approval link would trigger the Approve Workflow which creates an event to complete Main Workflow Task2. However, Main Workflow Task3(DECISION) would not be able to evaluate the decision as Task2(WAIT) does not hold any output for decision making. 

Is there a way to pass the payload of Approve Workflow task2(EVENT) and make this payload the output of Main Workflow task2(WAIT)?

Appreciate your guidance on this. Thanks very much.

**Comment by apanicker-nflx** [comment]
> Is there a way to just lock the task to a worker, and not allow any other worker to get the same taskId?

Conductor does not explicitly lock a task to a worker. Once a worker polls for a task, this task is set to IN_PROGRESS status and is then unavailable to be polled by another worker. You could technically use this in your case but `remains in progress for weeks` this could be an issue, since if the worker instance were to go down at anytime during this period, this task is essentially lost and would eventually be timed out by the server.

> Is there a way to pass the payload of Approve Workflow task2(EVENT) and make this payload the output of Main Workflow task2(WAIT)?

You can [set the payload of the event task](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/tasks/Event.java#L68) with the desired parameters so that the published event has the necessary data. The listener that completes a WAIT task in conductor will [propagate the event payload](https://github.com/Netflix/conductor/blob/master/contribs/src/main/java/com/netflix/conductor/contribs/queue/QueueManager.java#L125) as received which can then be used by the subsequent DECISION task in your workflow.

**Comment by apanicker-nflx** [comment]
Another approach to solving this use case could be to implement your `check_for_approval` worker in such a way that everytime this worker is invoked, it checks your system to see if approval has been granted for the user request. If not, it updates the task result with IN_PROGRESS status and a callbackAfterSeconds of 3600 seconds(for example). What this entails is that after 3600 seconds, this task will be available to be polled again by this worker. This worker would then do the same check again and update similarly or with COMPLETED status if approval is granted. The `callbackAfterSeconds` semantic on the task is heavily used by our users to implement such long running tasks scenarios.

**Comment by mcancio** [comment]
Thanks @apanicker-nflx for your comprehensive reply. I'm now able to pass on the event payload to the wait task.
