### ISSUE TITLE
some question about deprecated ack

### ISSUE THREAD

**Issue by MrLrf** [Netflix/conductor#1623]
1. Why is the ack mechanism deprecated in the new version? What are the considerations?
2. How to ensure that a task will not be executed by multiple workers after deprecating the ack mechanism?
3. I also want to ask how to stop the worker from executing this task after a task has been actively cancelled?

**Comment by apanicker-nflx** [comment]
> Why is the ack mechanism deprecated in the new version? What are the considerations?

The `ack` mechanism was not found to be optimal for several use cases due to the extra hop from the worker. Also, client side queueing on top of the queues in the server side meant thaat queue wait times for tasks was huge. It was also found that in some cases, a task could get timed out by simply waiting to be ack'ed on client side queues because worker threads were not available to process the task. 
With the new client architecture, a task is polled only if the client has available thread for processing it and the task is processed right away after it is polled instead of being held in a client side queue.

> How to ensure that a task will not be executed by multiple workers after deprecating the ack mechanism?

[The server actively acks the task](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/service/ExecutionService.java#L182) before delivering the task to the worker, and thus ensures that only a single worker instance is processing a given task.

> I also want to ask how to stop the worker from executing this task after a task has been actively cancelled?

This is not possible currently, since once a worker polls and receives a task from Conductor, the worker holds the task and the server is just waiting for a response from the worker with the TaskResult. However, if the task has already been canceled by then, the task result will be ignored.
