### ISSUE TITLE
Sporadic mysql connection issue

### ISSUE THREAD

**Issue by amishasthana** [Netflix/conductor#1653]
Hi Folks we are facing an issue in connecting to mysql(Aurora in AWS). We have SSL and TLS1.2 turned on.
Sometime it works fine and we can see in SSL debug logs that certificates get loaded and hikari pool is able to initialize.
However other times it fails. Looking at the log it seem that it may be way the modules are initialized and when the server start in Main.java. It seem there is race condition. Connection tried before the truststore get loaded fails, where as connections afterward works fine, and conductor goes into funky state.
Has anyone seen this issue?

**Comment by amishasthana** [comment]
It seem its related to our istio side car proxy. Its not initializing fast enough and thus from time to time initial connection breaks. Closing the issue.

**Comment by dhineshbabuelango** [comment]
Hi @amishasthana were you able to solve this issue
I am seeing this issue now only if I use istio sidecar

"HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5f37ca9f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
 hikaripool-1 - connection marked as broken because of sqlstate(08s01), errorcode(0)
