### ISSUE TITLE
if loopOver task within DO_WHILE times out and DO_WHILE has retries, doesn't work

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1655]
If a loopOver task within a DO_WHILE times out, the DO_WHILE fails (FAILED status) - from the documentation, that is expected. Unfortunately if the DO_WHILE has retries available, it is retried but the retried DO_WHILE task immediately comes back as FAILED and its loopOver task gets CANCELED (so not pollable). That is what happens the first time it is retried. After that the additional retries of the DO_WHILE just get set to FAILED with no retry of the loopOver and eventually the workflow fails.

I am trying to debug what is causing this behavior but it is pretty hairy with all the twists and turns. Has anyone seen this before?

**Comment by rickfish** [comment]
I am thinking about creating a pull request that adds a retryCount match when filtering the loopOver tasks to review. The problem seems to be that the current DO_WHILE execute() method looks at all past tasks as well as the current one and it shouldn't. Does anyone have any issues with me changing the stream filter to the below (basically adding a match on retry count)?

``		List<Task> loopOver = workflow.getTasks().stream().filter(t -> 
			(task.getWorkflowTask().has(TaskUtils.removeIterationFromTaskRefName(t.getReferenceTaskName())) 
			&& !task.getReferenceTaskName().equals(t.getReferenceTaskName()) 
			&& task.getRetryCount() == t.getRetryCount())).collect(Collectors.toList());
``

**Comment by manan164** [comment]
Hi @rickfish , Thanks for pointing out.
The idea was when any loopOver task failed we should retry complete iteration from first loopOver task. If this is not happening then its bug. The reason is, if we start from the loopOver task which failed then the condition inside the execute method will be complex. We have to take care of all loopOver tasks retryCount also. Please create PR for the fix.
Also, DO_WHILE task itself is very slow because of applying the filter on all the workflow tasks. Please change the condition if you want.

**Comment by rickfish** [comment]
Thanks @manan164. I just created PR #1657 for this fix. It is really difficult to tell if this will cause any side effects but I don't think it will. DO_WHILE is a tough one to test all scenarios - thanks for taking this on - I'm sure it wasn't an easy one to implement.
