### ISSUE TITLE
Registering Netflix Conductor with a Eureka server and making it discoverable. 

### ISSUE THREAD

**Issue by krishnaputhran** [Netflix/conductor#1689]
1. How I can make my netflix conductor discoverable and get registered with an eureka server.
2. Assuming it gets registered on a eureka server, how I make HTTP requests through HTTP task to another microservice registered in the eureka server. I want to use service name in my uri than the ipaddress or hostname. for eg: through the HTTP system task in my workflow, I want to make a call to a micro service registered with my eureka server. Conductor while running my HTTP task should resolve the service name by doing service discovery.
 for eg: my HTTP task uri is something like this. uri:http://{serviceName}/enpoint.
Any help on this is greatly appreciated. 
I am not sure how vipAddress will be of help. I tried using it without knowing whether my conductor is discoverable. i

**Comment by MingningShao** [comment]
1.It seems that Conductor do not registered with an Eureka server currently. you can do it by yourself, like deploy an eureka server and then register the conductor;
2.A new eureka based worker will work if you want service discovery;
3.It's a necessary function(service discovery) since we are orchestrating micro-services.
