### ISSUE TITLE
JSONPath Validation failed - parameter value invalid

### ISSUE THREAD

**Issue by jansonz** [Netflix/conductor#1749]
Hi,

Migrating from 1.12.9 to 2.27.5 Conductor and face issues migrating over workflows.
When posting I get the following ERROR back:

`{
    "status": 400,
    "message": "Validation failed, check below errors for detail.",
    "retryable": false,
    "validationErrors": [
        {
            "path": "registerWorkflowDef.arg0",
            "message": "key: input_data input parameter value: get_asset_1.output.response.json.Item.SmoothFolders[*].Manifests[?(@.ManifestTypeId=='1' && @.TypeName=='Feature')].FtpLink.Href is not valid"
        }
    ]
}`

Seem that Conductor fails to validate the JSONPath, however it's working on Conductor 1.12.9 as well as the online JSONPath validators.

Seems that the part which conductor doesn't like is this:
`?(@.ManifestTypeId=='1' && @.TypeName=='Feature')`

I seem to be able to post workflow with either `?(@.ManifestTypeId=='1')` or `?(@.TypeName=='Feature')`, but not both with "&&" in between. Is there any known validation bug which could affect this?

My workflow step definition:
`{
            "name": "request_task",
            "taskReferenceName": "get_remote_filepath_1",
            "inputParameters": {
                "request": {
                    "url": "http://stringparser.xxxx.com/v1/regex/",
                    "json": {
                        "input_data": "${get_asset_1.output.response.json.Item.SmoothFolders[*].Manifests[?(@.ManifestTypeId=='1' && @.TypeName=='Feature')].FtpLink.Href}",
                        "pattern": "${workflow.input.provider_config.properties.filename_pattern}"
                    },
                    "method": "POST",
                    "headers": {
                        "Accept": "application/json",
                        "Content-Type": "application/json"
                    }
                }
            },
            "type": "SIMPLE",
            "startDelay": 0
        }`

Thank you.

**Comment by dcore94** [comment]
A rather similar issue ...
I am trying to filter out one record from a list returned by another task with JSONPath and pass it as input of another task. The code i use in the input variable definition is: `${get_records.output.body[?(@.name == '${workflow.input.selectedname}')]}`. The expression in the predicate is expanded correctly bout the overall expression no. Thus on the worker resulting in: `${get_records.output.body[?(@.name == 'John')]} `instead of the list of records matching the name. What am I doing wrong here?
Same query on a JSONPath evaluator I found online the filter worked ...
When I hardcode the name as in `${get_records.output.body[?(@.name == 'John')]}` I even get a validation error for the expression not being valid ... "message": "key: body input parameter value: `get_records.output.body[?(@.name == 'John')] ` is not valid.

**Comment by kishorebanala** [comment]
@jansonz @dcore94 These are Workflow and Task definition validation errors originating from: https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/utils/ConstraintParamUtil.java#L71

For ```"message": "key: input_data input parameter value: get_asset_1.output.response.json.Item.SmoothFolders[*].Manifests[?(@.ManifestTypeId=='1' && @.TypeName=='Feature')].FtpLink.Href is not valid" }```, the validation is complaining about the white space in this text (which might've been added to avoid other issues).

Please refer to this file as you work through debugging validation errors in above Json path selector.

**Comment by jansonz** [comment]
@kishorebanala you are completely correct, when changing `[?(@.ManifestTypeId=='1' && @.TypeName=='Feature')]` to `[?(@.ManifestTypeId=='1'&&@.TypeName=='Feature')]` my issue seems to be resolved 😃 Thanks.

Issue reported by @dcore94 seems to be something else then.
