### ISSUE TITLE
INTERNAL_ERROR - The Task defined as a sub-workflow has no workflow definition available

### ISSUE THREAD

**Issue by jansonz** [Netflix/conductor#1751]
We are migrating Conductor from 1.12.9 to 2.27.5 and have notice a issue that it's not possible anymore to pass to tasks sub-workflow names dynamically:

Error:
`{
"code": "INTERNAL_ERROR",
"message": "INTERNAL_ERROR - The Task ${get_provider_configuration_1.output.response.body.properties.processing_workflow} defined as a sub-workflow has no workflow definition available ",
"retryable": false,
"instance": "conductor-server-deployment-xxxx"
`

We use external configuration DB where we dynamically configure provider processing_workflow. Has this option been removed?

**Comment by apanicker-nflx** [comment]
One of the changes that were added to Conductor 2.0 was the validations that require workflow and task definitions to be registered in Conductor before starting a workflow. This is equally applicable to sub workflows as well.
Having said that however, with the [v2.27.1](https://github.com/Netflix/conductor/releases/tag/v2.27.1) release, you can provide your subworkflow definition as part of your subworkflow task instead of pre-registering it.
