### ISSUE TITLE
Performance Improvement: Using NIO patterns for Elasticsearch indexing

### ISSUE THREAD

**Issue by mdepak** [Netflix/conductor#1775]
Elasticsearch indexing is one of the main bottlenecks in the Conductor's system performance. Async indexing and batched indexing helps greatly in improving the overall indexing. But one of the problems with async indexing is during high throughput scenario is the number of index requests getting backlogged exponentially over time. This can be solved by increasing the number of the thread count of the async index worker thread pool. But having so many threads are not ideal as they are mostly waiting for I/O and takes up the heap. 

Possible Solution:
Use Netty/similar NIO framework to process index requests in a non-blocking fashion. 

Please let me know your thoughts on the problem/solution.

**Comment by apanicker-nflx** [comment]
@mdepak Agreed that in high throughput scenarios, ES indexing is one of the main bottlenecks. Further, the root cause here is the latency of the ES cluster to indexing requests at high throughputs. To mitigate this, one of the solutions we have considered is to use an intermediate Kafka layer which acts as a buffer for the indexing requests. Conductor writes all indexing requests to a Kafka topic which will then be consumed from an Apache Flink job/Java app with Kafka consumer. This job will perform the indexing  in the ES cluster. We are currently using this architecture in our environment and have seen greatly increased performance. Additionally, using Flink's checkpointing and Kafka's durability guarantees, we have also seen improvements in the consistency and synchronization of data between the primary store and the ES index. We hope to wrap this back into the Conductor OSS project as part of the next major version upgrade (3.0)

**Comment by mdepak** [comment]
Thanks, @apanicker-nflx for the quick response. Transferring the pending request to the external queue (which has low latency than elasticsearch) like Kafka to alleviate the heap usage of the conductor system should be helpful. Since Kafka consumers can be scaled independently, it should handle high throughput scenarios. Thank you!
