### ISSUE TITLE
Jedis connection timeout when conductor is running on heavy load

### ISSUE THREAD

**Issue by simarpal** [Netflix/conductor#1799]
The following image shows the failed HTTP.
![image](https://user-images.githubusercontent.com/25483663/87984410-ed6e4f00-caa7-11ea-9be8-6803df94447f.png)

Different workflows are failing on different task 
**Common pattern**:  
1) All failed task in all workflow is HTTP.
2) All Got 409 on the first try even though the target server creates a new record.
**3) The poll count is 2 (seems like conductor task send two HTTP requests on the same HTTP task)**
4) The failed task took a long time to finish. 

This problem is not related to timeout as timeout was set to a very long duration of 10 min.

**Conductor log error/warnings**
![image](https://user-images.githubusercontent.com/25483663/87984925-c1070280-caa8-11ea-802e-f14d293b4d82.png)
![image](https://user-images.githubusercontent.com/25483663/87984943-cebc8800-caa8-11ea-8b77-f0acfe23ed37.png)

**Comment by simarpal** [comment]
@manan164 any suggestion on this. This is not only happening to HTTP but worker task as well. The conductor is unable to poll timely and connection timeout.

**Comment by apanicker-nflx** [comment]
From the exception posted above, this seems to be failing connections to redis-server. Could you please verify the configurations of your redis server?

**Comment by indiv0** [comment]
So in our case (I work with @simarpal) it appears to be caused by a combination of:
1) RDB & AOF (everysec) persistence being enabled in Redis
2) Our custom workflow archiver module not clearing out old workflows, so
3) Redis uses large amounts of memory for storage due to old data
4) Writing RDB to the disk while under heavy write load due to AOF (everysec) causes severe latency spikes (>2s) which triggers the redis connection timeout.

To resolve this, we'll likely move to Conductor's contributed workflow archival module (so workflows get cleared out of redis faster). However @apanicker-nflx I was wondering, why does the `indexDAO.searchForArchivableWorkflows` method now have this:
```java
.must(QueryBuilders.rangeQuery("endTime").lt(LocalDate.now().minusDays(archiveTtlDays).toString()).gte(LocalDate.now().minusDays(archiveTtlDays).minusDays(1).toString()))
```
in the query, it used to just have:
```java
.must(QueryBuilders.rangeQuery("endTime").lt(LocalDate.now().minusDays(archiveTtlDays).toString()))
```
This narrows the search window down to 1 day. If the archival module was down for >1 day this means that some workflows might never get archived. So why the new limit on the query?

**Comment by indiv0** [comment]
Also, on a semi-related note: is it possible to have multiple implementors for `WorkflowStatusListener`? If we plan to use conductor's archive module, and another module of our own (unrelated to archiving), will we need an intermediary layer that calls `onWorkflowCompleted` for both these modules?

**Comment by apanicker-nflx** [comment]
@indiv0 The observations about the `searchArchivableWorkflows` method are correct, the limit was introduced to constrain the bound of the ES query. This was done as an experimental task but was never removed. Please feel free to refactor/redo this method.

> Is it safe to set archiveTtlDays to -1 (i.e. same-day archival) if we're using synchronous indexing? Could that cause issues due to premature workflow archival? That is, could this result in us archiving workflows before they've been re-indexed, and would that be a problem?

In the case of synchronous indexing, you can use immediate archival upon completion. The latency for loading such workflows would be slightly higher since fetching data from ES is slower than fetching data from redis (in your case).

> is it possible to have multiple implementors for WorkflowStatusListener? If we plan to use conductor's archive module, and another module of our own (unrelated to archiving), will we need an intermediary layer that calls onWorkflowCompleted for both these modules?

In the current setup, you would need an additional intermediary layer.

**Comment by indiv0** [comment]
Thanks for the information!
