### ISSUE TITLE
Is Kafka eventing likely to be in version 3.0 of Conductor?

### ISSUE THREAD

**Issue by NeuralViva** [Netflix/conductor#1804]
Hi,

I've been looking into Microservice orchestrators for my organisation and Conductor fits most of our requirements really well.

One missing thing was the ability to start a process via a message on a Kafka Topic. I saw this [PR](https://github.com/Netflix/conductor/pull/672) which was closed in 2019 and was wondering if anything like this is on the roadmap for Conductor?

Great project BTW.

**Comment by rickfish** [comment]
I have this working on our local implementation. I keep getting distracted from contributing it back though. It is working great but contributing it back is the tough part - test cases, documentation, etc. I also have added the ability to send any errors during the processing of the event to an 'errors' topic and to send an email if there is a failure. Also I have added jaas security capability to it so that you can specify a jaas config file, etc.

Again, I have to find time to make it contributable but would be happy to share what I have if you like - not sure logistically how to do that though...

**Comment by kishorebanala** [comment]
This definitely seems like a valuable addition, but might take a while until we reach there in our roadmap. We'd very much welcome the discussion and contribution from the community.

**Comment by NeuralViva** [comment]
Thanks for the responses, I'm currently asking around in my org to see if there is any appetite to support this.

I'm also happy to contribute to any efforts (although my Java is a little Rusty), is there a recent fork available to work on @rickfish?

**Comment by rickfish** [comment]
@NeuralViva do you have access to https://github.com/rickfish/conductor? That is my fork. The branch is feature/kafka-event-source. There is a document under conductor/docs/docs/kafkaeventsource.md that should have enough info to get you started. I can use some suggestions if the document does not cover everything or is confusing. I currently do not have any test cases yet.

**Comment by NeuralViva** [comment]
Sorry for the really slow reply on this, busy few weeks. 

I can access your fork, from reading the docs your solution looks really fully formed 👍 

I'll pull your fork today and get it running, and start looking at some tests.

**Comment by rickfish** [comment]
I just created PR #1911 for this. I am sure there will be lots of back and forth before it is accepted though.
