### ISSUE TITLE
PR #1748 causes a limit to the number of 'conductor' events that get polled

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1806]
PR #1748 seems to limit the number of event types that are polled by the DynoObservableQueue implementation because of the new Scheduler that it uses. The new 'workflow.event.queue.scheduler.poll.thread.count' property puts a hard limit on the number of 'conductor' event types that get polled. I don't think that was the intent because adding a new event handler should not require that thread count to have to be changed, right? 

The symptoms are that, if this is set to 4 and there are 5 'conductor' event handlers, only 4 of those event types will be polled for and events of the the last event type will never get processed.

How should I be setting this property so that no matter how many event handlers I add it flexes to poll for all of them?

If it cant be set to be dynamic and grow, why not just use Schedulers.io() for the Observable like it was doing before? Seems like that fits the bill unless I don't know about a pitfall with that one.

**Comment by apanicker-nflx** [comment]
@mdepak Can you please comment on this change?

**Comment by mdepak** [comment]
Using the Execution scheduler does not limit the number of events that can be polled. In the implementation, there will be one instance of ObservableQueue implementation per event type. Singleton scheduler object will be used across all the observable queues and threads from this scheduler thread pool will be used for polling.

In earlier implementation Computation scheduler is used and that has upper bound on the number of threads in pool equal to the CPU cores. With the computation scheduler, there will more contention for the acquiring threads. As per docs, the computation scheduler is recommended for CPU intensive tasks, and polling from external queues is i/o bound task.

Using Schedulers.io() is not ideal here since, if one of the external queues is misbehaving, the scheduler might end up creating more threads while others are still waiting for the i/o. This can consume more heap space and might lead to OOM. With the Execution scheduler, one can control the number of threads that are used for polling from queues.

Ideally, if the number of threads is equal to the event types there will not be contention. But since the poll operation is not long-running, it should not affect having lesser thread count.

@apanicker-nflx  Do you think adding README documentation for the property will help? If so, I will add documentation for this property and similar ones. 

@rickfish  Please let me if there are any further questions.

**Comment by rickfish** [comment]
@mdepak the reason I opened this issue is because we found this to be a problem. When we deployed the new code, we noticed that only one event type was being processed. We run our instance(s) of conductor on OpenShift, RedHat's Kubernetes platform. Each instance (pod) is given fractions of cores. In our case, each pod only needed one core. The new code, because there was only one core and we used the new property's default, caused there to be only one thread in the pool and hence only one event type was being polled. 

You can duplicate this by setting the new property (thread count) to 1, adding two event handlers and creating an event of each type. Only one will be processed. I did a lot of debugging on this and found that to be the case. Not saying there isn't something else going on here but I don't think so.

On my local machine I set the property to 1 and ran Conductor as a standalone Java app and witnessed the same behavior. The previous version of Conductor worked fine. We have several event handlers and all events for all types were processed. With the new code, events of only one type were processed over a period of a couple of weeks. That is what alerted us to the issue.

Not sure what to do from here other than coming up with a test case for this scenario but I don't have the time to do that right now.

Note that this is using the DynoObservableQueue implementation with 'conductor' events.

**Comment by james-deee** [comment]
@mdepak and @apanicker-nflx can someone respond to @rickfish about this?

We are seeing some odd behavior around Conductor events not getting processed correctly either, and I'm wondering if this is what we are hitting as well.

**Comment by rickfish** [comment]
I never did hear back from @mdepak. This is most definitely a problem for
us (not sure why nobody else has reported it) and we have fixed it in our
Conductor codebase. Our solution was to change (in DynoObservableQueue)
this:
Observable<Long> interval = Observable.interval(pollTimeInMS, TimeUnit.
MILLISECONDS, scheduler);
to this:
Observable<Long> interval = Observable.interval(pollTimeInMS, TimeUnit.
MILLISECONDS, Schedulers.io());

**Comment by james-deee** [comment]
@rickfish thanks. Yeah I dont understand how no one is hitting this either. Maybe just not a lot of events being used? But it's 100% a problem. We can confirm we were seeing the same thing as you.

Thanks, we'll try your suggestion with the Schedulers.io()

**Comment by mdepak** [comment]
@rickfish Apologies for the delay. I have verified using the scenario that you mentioned and it seems to be a problem when the number of threads in the scheduler is less than the number of event types.
I will send the PR shortly to restore the previous behavior without this newly added config. After that, I will try to dig into the RxScheduler implementation to understand the root cause of why Execution schduler is allocating thread to each observable instead of sharing threads between observables.

**Comment by rickfish** [comment]
@mdepak thank you
