### ISSUE TITLE
Is this better to use json instead of toString()?

### ISSUE THREAD

**Issue by kensou97** [Netflix/conductor#1852]
https://github.com/Netflix/conductor/blob/856de56963b221cb29a83048b2120523fe4d243d/common/src/main/java/com/netflix/conductor/common/run/WorkflowSummary.java#L119

I get workflowSummary from listener, however i can't process input and output because they're map.toString format...

**Comment by apanicker-nflx** [comment]
The summary objects (WorkflowSummary and TaskSummary) are used to index data in Elasticsearch. Converting the input and output to string during indexing helps provide full text search ability on these fields while limiting the number of indexed fields in the index, since the inputs and outputs of every workflow would be different.

Consider using an ObjectMapper to deserialize this string into a Map again before using this.
