### ISSUE TITLE
no tasks listed in the search tasks API response

### ISSUE THREAD

**Issue by mishika29** [Netflix/conductor#1855]
I am trying to use the following API for conductor in order to search for registered tasks:
curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/tasks/search?size=100&freeText=*'

The response received is:
{"totalHits":0}

Whereas the tasks have already been registered and are listed well for the get all tasks API
The same is the scenario I face with the search workflow tasks. The workflow is registered and listed for get all workflows API but there are no workflows listed in the response for search workflow API

What can be the issue here?

**Comment by kishorebanala** [comment]
@mishika29 Can you confirm if the Elastic search indices created by Conductor contains any data? If not, you can debug and trace the workflow indexing from workflow execution path. Otherwise, you can debug the task search API to see how the above request is transformed to relevant Elastic search query.
