### ISSUE TITLE
pass through workflow input to dynamic task 

### ISSUE THREAD

**Issue by HenryLauu** [Netflix/conductor#1881]
I am using dynamic task type to run different task with different task input which is given by workflow input, how can i pass through those inputs to dynamic task?

**Comment by kishorebanala** [comment]
@HenryLauu Does this help? https://netflix.github.io/conductor/configuration/systask/#dynamic-task

If not, Can you provide an example for what you're trying to achieve please?

**Comment by HenryLauu** [comment]
Thanks @kishorebanala . Let say I have taskA with paramA, taskB with paramB.  Those two params will be give by workflow input. What i need is pass workflow input to dynamic task.

now figure out this by following workflow:

- task1:  agent task, which get workflow input and set output data including two key: dynamicTasksInputJSON,dynamicTasksJSON
- task2: dynamic fork task, get task_type and input from previous task's output
- task3: join task

any suggestion would be appreciated

**Comment by kishorebanala** [comment]
Hey @HenryLauu , I'm confused by the interchanged use of `dynamic task` and `dynamicTasksInputJSON, dynamicTasksJSON` which belongs to `dynamic fork task`. Are you planning to use https://netflix.github.io/conductor/configuration/systask/#dynamic-fork instead of https://netflix.github.io/conductor/configuration/systask/#dynamic-task ?
