### ISSUE TITLE
Achitecture / Enteprise implemntation questions

### ISSUE THREAD

**Issue by cmrenus** [Netflix/conductor#1906]
Hey there, I have been looking at implementing Conductor in our company but had a bunch of questions regarding some decisions and just things I couldnt find. I've scoured through all the other issues and what I can find, so I'll try not to ask questions that may have already been asked :) 

1. Looking through documentation, I see internally you have moved away from Redis at the persistence layer to Cassandra. Was curious what was the motive there? 

2. Through looking at other issues, I see there have been some things about slowness of Http system tasks due to the async behavior. Is the http thread pool configurable? And at what point would exhaustion occur if that was made sync and then does the conductor server share the same threads for system tasks with the http system tasks?

3. To piggy back off the previous question, if exhaustion or wait time becomes high, would it then make sense to create my own worker to make http requests so that specific thing can be horizontally scaled? My application is for order processing which will mostly be api based validations and just for decoupling purposes, would prefer keeping http based as common communicatoin mechanism as well so I can have that separation. 

4. Another post I saw was mentioned you all have Kibana dashboards built made for the conductor metrics. Is there anyway you would be able to share those templates out? 

5. Are you still using Dynoqueues for the queueing layer? What was the decision behind using Dynomite as well? Redis provides HA and sharding, so was there something about it that did not fit well? Again saw a post related that would then need a conductor server per AZ. Why is that? 

6. Do you have any numbers on load with a basic workflow? Just how things handle since it is async. Whether you tested with single node and how you scaled there? 

7. Would you be able to provide link to any more documentation regarding gRPC? I cant seem to find anything much but saw it was added in 2.0

Thanks,

**Comment by cmrenus** [comment]
Oh and what is currently being used for queues? I see here https://github.com/Netflix/dyno-queues that the project is no longer supported

**Comment by aravindanr** [comment]
1. There are two major issues we have with Dynomite as workflow execution store that motivated us to migrate to a different data store:
Dynomite cannot be scaled horizontally without downtime, which limits the number of conductor instances we can have and the amount of data we can store. Dynomite doesn't provide transaction support for multiple writes across different data structures, this causes intermittent data inconsistency issues for Conductor.
2. All system tasks (including HTTP) share the same thread pool. Do understand that Conductor is not built for speedy execution of tasks. Conductor is an async system which guarantees execution of a task but doesn’t provide any specific time limits. We haven’t measured the bottlenecks that would be introduced if HTTP becomes a “sync” task.
3. This entirely depends on your use-case and scale. To scale HTTP tasks, the conductor server application needs to be scaled. If the same behavior is implemented as a [simple task](https://netflix.github.io/conductor/configuration/taskdef/), it can be scaled independently of the conductor server.
4. We will see if this can be shared.
5. Internally, we use a queuing system that is built on Redis. We have plans to contribute a queue implementation to Conductor, that is based on Redis, but there is no ETA for it as of now. It is fairly simple to write a QueueDao implementation with Redis and its Lua script support.
Regarding the need for a conductor server per AZ, this is due to the limitation of DynoQueues which require the client to be present and polling from the same AZ as the queue shard. If you choose to not use DynoQueues, then this does not apply.
6. TBD
7. We added some documentation regarding the implementation of the gRPC modules [here](https://netflix.github.io/conductor/technicaldetails/#grpc-framework). Quite a bit of this is also scattered as javadocs through the code.
