### ISSUE TITLE
Support for Rollover Elasticsearch indexing

### ISSUE THREAD

**Issue by mdepak** [Netflix/conductor#1937]
**Overview:**
Conductor uses elasticsearch for indexing workflows, tasks, and other documents. This leads to a pile-up of data in elasticsearch and reduces the indexing performance with increased latency. 
One solution is to search for the older data periodically and delete the documents from the elasticsearch. But this approach does not work for high throughput scenarios, where several thousands of documents need to be deleted and this is additional IOPS to the elasticsearch cluster. This way of search and delete does not allow us to control the size of the shards in elasticsearch. To address this we can leverage the rollover indexing feature from Elasticsearch.

**Proposed Solution:**

Using the rollover indexing feature in elasticsearch can help address this problem. One caveat is that the conductor updates the documents and hence it cannot be used explicitly. So we can leverage the metadata in the documents to decide the index during the update requests. For all the documents, start time/created time or similar is set before the document is indexed first. During the update operation, we can leverage the workflow/task creation time to decide the index to update the documents. If the document is missing in the calculated index, then retry can be done in the next consequent rolled-over index due to lag in the rollover request.  This way the duplicate documents can be avoided in the index. Further, for the search queries, index prefix naming pattern can be used, and for the get/delete by document id queries, the retry can be performed on the rolled over indices in the descending order of index creation.

With this approach, only workflow/tasks running during the rollover index switchover needs to go over additional update retry with the previous index.

Rollover can be supported for both synchronous and asynchronous indexing. Indexing the task documents requires some changes in the synchronous indexing mode, where currently the document is always overwritten and requires segregation between creation and update of document. In the case of asynchronous indexing, since the task document is always updated in the terminal state, it can be created once and does not require an update.
We have implemented this feature on ES 5 REST and testing it and working on making the changes for rest/transport modes of ES 6 as well. 

@apanicker-nflx  @kishorebanala  Please let me know your thoughts/feedback on the approach.

**Comment by apanicker-nflx** [comment]
@mdepak Thank you very much for write-up. While rollover indices do help, the problem with maintaining the indices here is that workflows can run for an arbitrary amount of time (seconds to months). In these cases, it is not possible to drop older indices based on a fixed time interval. As stated in your proposal, updates to documents refresh the age of a document within an index and deleting such a document (because index age is old) would not be ideal. 

Having said that however, there is definitely a use-case (workflows that run for short periods of time) where the proposed solution would be helpful. When implementing this proposal, please ensure that it is controlled by a feature flag such that it can be enabled/disabled based on the use case. For the rest of the use cases where long running workflows are used, a delete by query operation on the ES cluster could be used to clean up the older documents where the query can be used to control which documents need to be deleted.

**Comment by mdepak** [comment]
@apanicker-nflx Thanks for the feedback. I will ensure this feature is controlled by the config.

**Comment by Deeksha4** [comment]
Hello @mdepak , @apanicker-nflx , 
We have a similar use case where in we require rollover for elastic search. Was this issue merged? or is roll over policy for workflow,task indexes configurable through some other property?
