### ISSUE TITLE
Workflow Details/Data in Elastic Search Index is out of sync 

### ISSUE THREAD

**Issue by ravisund** [Netflix/conductor#1974]
Hi,
   I had setup a conductor instance, created  few sample workflow definitions and created workflows. When called the search API (e.g. /api/workflow/search?size=100&query=status%3D'RUNNING'), it is returning the workflows which are not matching the criteria. 
In my example, i searched for all workflows in RUNNING state. But the results contain couple of workflows in PAUSED state. 
1) I am using elastic search 5 and i haven't enabled async indexing.
2) I looked at the conductor code ExecutionService.search() . It fetches the workflow ids as search results then fetch the actual workflows from ExecutionDAO. 
3) To further debug, **i executed search query directly on elastic search**. For those couple of workflows, the **status** attribute value is RUNNING in elastic search document and PAUSED in workflow data store (in my case, it is postgres database)
4) Most importantly, if i use conductor UI, it still gets the same results (i.e. including those couple of workflows in PAUSED state), but the UI is filtering out those two workflows and only displays the workflows in RUNNING state.

Is it a known issue ? Is there a fix for this ? does conductor ensure that both elastic search data & execution data are in sync ?

**Comment by apanicker-nflx** [comment]
@ravisund This is odd, the behavior that you have listed above is expected when you have async indexing enabled. This is because in this case, workflow updates (status changes, etc) are only indexed when the workflow moves to a terminal state. However, you mention that async indexing is not enabled in your case. Could you please double-check this? Also, I would recommend you to try to debug the server, specifically the [ExecutionDAOFacade](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java) to see if the indexing requests are actually making it through.

**Comment by ravisund** [comment]
@apanicker-nflx thank u for getting back. 
In my case, i noticed this for few workflows only. when a transition happens for that out-of sync workflow (e.g. when i resumed a workflow from PAUSED state), the index was updated.  

because those workflows were in paused state for many months (this is a test setup). I will update this thread if this issue happens again.
