### ISSUE TITLE
Example client reports ClientHandlerException when receiving octet-stream media type

### ISSUE THREAD

**Issue by jeremy-l-ford** [Netflix/conductor#2010]
When the sample client found in client/test source executes, a ClientHandlerException is thrown.  The Spring rest controller for task polling is returning a null task which seems to be interpreted by Spring to result in a media type of octet-stream instead of application/json.

To avoid this issue, the server could return a ResponseEntity and force the media type to be json.  Another option might be returning a 404, but the client would need to handle this as well.

**Comment by apanicker-nflx** [comment]
Assuming that you are running into this issue in the 3.0 branch, thanks for reporting this.

This is because of the difference in behavior between the response from Spring's tomcat layer v/s the Jetty server used in the Guice implementation in 2.x 
To fix this, you would need to add logic similar to the `/tasks/taskId` [endpoint here](https://github.com/Netflix/conductor/blob/3.0/rest/src/main/java/com/netflix/conductor/rest/controllers/TaskResource.java#L116-L117). We will incorporate this fix in our next set of changes but this should help to unblock you.
