### ISSUE TITLE
Mixed usage of multiple persistent implements

### ISSUE THREAD

**Issue by HenryLauu** [Netflix/conductor#2016]
We have lots of task and workflow definitions which were store in mysql. for performance purpose, we are planning to use redis as backend queue . Is it possible to use mysql for definitions and redis for queue? Any suggestions would be helpful.

**Comment by aravindanr** [comment]
It is possible but it can't be accomplished using configuration. It requires code changes. You can fork the code and create your own Guice module and wire in any implementation of the DAOs as needed. Also, note that we are undergoing a transition from Guice to Spring Boot and we are planning to make the DAO selection more granular in that version.  If you are inclined, the issue is [here](https://github.com/Netflix/conductor/issues/2017) and the 3.0 [branch here](https://github.com/Netflix/conductor/tree/3.0).
