### ISSUE TITLE
Does our workflow inputParameters support type like 'MultipartFile'

### ISSUE THREAD

**Issue by WavyPeng** [Netflix/conductor#2052]
Hi, we have a use case that we need to deal with picture. Therefore, the input parameter maybe 'MultipartFile'. 
Does our Java SDK supports this?

**Comment by apanicker-nflx** [comment]
The input parameters to a workflow is a map of string to objects. In this case, since Conductor is to be used as an orchestrator for scheduling and executing the tasks processing the picture, it is recommended to provide the locations of your picture files in the input parameters rather than passing binary blobs of data through the workflow engine.
