### ISSUE TITLE
where's the defination of isolation group id for a workflow?

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#2055]
see the attachment
![20210118115912](https://user-images.githubusercontent.com/11346379/104871081-2028cf80-5985-11eb-869d-22e80e624256.jpg)

**Comment by apanicker-nflx** [comment]
There was a slight typo in the documentation which has been fixed. The `name` parameter for the WorkflowTask in the screenshot above should be `encode_task` to match the task name in the task definition in the example [here](https://netflix.github.io/conductor/configuration/isolationgroups/). 
Since the isolation group id is set in the task definition, this task will now be queued up in an isolated queue `HTTP-myIsolationGroupId` and will not share the same queue `HTTP` as other http tasks. This is applied at a task/queue level and is not visible within the workflow.

**Comment by andyyumiao** [comment]
> There was a slight typo in the documentation which has been fixed. The `name` parameter for the WorkflowTask in the screenshot above should be `encode_task` to match the task name in the task definition in the example [here](https://netflix.github.io/conductor/configuration/isolationgroups/).
> Since the isolation group id is set in the task definition, this task will now be queued up in an isolated queue `HTTP-myIsolationGroupId` and will not share the same queue `HTTP` as other http tasks. This is applied at a task/queue level and is not visible within the workflow.

Ok Thanks, and as I expected, it seems to be a documentation problem, lol
