### ISSUE TITLE
Conductor does not retain the json format of the data passed to k8s job task

### ISSUE THREAD

**Issue by shank1204** [Netflix/conductor#2071]
Conductor Version - **2.27.2**

**Steps** - 
1. Create a workflow where K8s job task is added in it.
2. This K8s job task has one of the argument in job spec pointing to the json field data in workflow input. e.g. _${workflow.input.**jsondata**}_ where 'jsondata' field will have a json format value in workflow input
3. Execute such workflow with a workflow input e.g.  
 _{
	"workflowId":"<WORKFLOW ID>",
	"version":1,
	"input": {
         "**jsondata**": {
              "field1": "value1",
              "field2": [
                 "test1",
                 "test2"
                  ]
               }
            }
}_
4. Check the input data of the K8s task 
Expected result - Since 'jsondata' field has json format data , same should be passed to k8s job task as input
**Actual result** - json data is changed automatically by conductor into HashMap format where all ":" characters are changed to "=" and double quotes are removed from the field names.

**Comment by kishorebanala** [comment]
@shank1204 Can you provide more details to help reproduce this please? Also, which endpoint is used to start the workflow? And how is the start workflow object created?

**Comment by flavioschuindt** [comment]
Hey @kishorebanala,

First, sorry if this is too long. Just trying to give many details as possible.

I work with @shank1204 and was helping him with it. So, to reproduce is like this:

* Create a workflow with a task type SIMPLE (We didn't test with other types, but probably will happen);
* In the inputParameters field for this task, say that you have this:

```json
{
  "k8sjob_request": {
    "resources": "${workflow.input.resources}"
  }
}
```

Say also that, just for the sake of example here, workflow.input.resources = ```{"a":"b"}```.

Try to invoke the workflow. ${workflow.input.resources} is a json and is indeed added as a plain json inside the resources property. ```k8sjob_request``` property in this case will be:

```json
{
  "k8sjob_request": {
    "resources": {"a":"b"}
  }
}
```

This is expected and correct behavior.

Now try to do this:

```json
{
  "k8sjob_request": {
    "resources": "apiVersion: batch/v1 ${workflow.input.resources}"
  }
}
```

The simple fact that you add a simple string (```apiVersion: batch/v1``` is just an example, could be any string) before the actual input parameter, makes the ```${workflow.input.resources}``` be added as a kind of HashMap content instead of plain json.

```k8sjob_request``` property in this case will be:

```json
{
  "k8sjob_request": {
    "resources": "apiVersion: batch/v1 a=b"
  }
}
```

And we would expect actually to be:

```json
{
  "k8sjob_request": {
    "resources": "apiVersion: batch/v1 {\"a\":\"b\"}"
  }
}
```

Maybe I am wrong, but what I think is happening is that conductor deserialization is understanding the entire data in this case as a string and issuing a ```toString``` or something similar and then the json representation of this is Java returned by the deserialization process is a Map.

We have a workaround for this now which is quote the entire ${workflow.input.resources} in the workflow start execution endpoint and then everything is a string. The drawback of course is that if I need to extract any inside information from the ${workflow.input.resources} like ${workflow.input.resources.**anything**} I simply can't do it because it is now a big string.

**Comment by aravindanr** [comment]
The JSONPath library that Conductor uses for json interpolation does not support this behavior. JSONPath sees the expression as a string uses the String representation of `${workflow.input.resources}` which is a `java.util.Map`.

**Comment by flavioschuindt** [comment]
Hi, @aravindanr. Thanks for replying.

So, is there any plan to change it? From my understanding, if I pass a json as input I would expect that this would still be a valid json and not a map. For example, this blocks some use cases where I want to call any http downstream services that is accepting a json. Unless I go in this downstream services and convert again the map to json or stringfy the input in the workflow. In both cases, I would have to do changes here and there to accommodate it.

**Comment by aravindanr** [comment]
The JSONPath library is customizable. Here's a similar question about JSONPath in [SO](https://stackoverflow.com/questions/52078224/java-jsonpath-extract-nested-json-object-as-string). Unfortunately, this is not a high priority and we won't get to it in the near future 

@flavioschuindt @CHURLZ if you have the time, we highly encourage you to contribute.
