### ISSUE TITLE
DecisionTask Printing Both Routes

### ISSUE THREAD

**Issue by btafarelo** [Netflix/conductor#2097]
Hi

As you can see my DecisionTask is taking a path but showing execution in both sides (the bold line and the green step).

![image](https://user-images.githubusercontent.com/3848106/108411815-5fb73580-7229-11eb-9763-4c69729f43a6.png)

`{
      "name": "Should_Not_Run",
      "taskReferenceName": "Should_Not_Run",
      "inputParameters": {
        "ispst": "${workflow.input.req.simulationParameters[0].simulationType}",
        "isp": "${workflow.input.req.simulationParameters}",
        "st": "${workflow.input.simulationType}",
        "sp": "${workflow.input.SimulationManager}"
      },
      "type": "DECISION",
      "caseExpression": "($.ispst == $.st || $.ispst == null || $.isp == null) && $.sp != null",
      "decisionCases": {
        "false": [
          {
            "name": "Abort",
            "taskReferenceName": "Abort",
            "type": "TERMINATE",
            "startDelay": 0,
            "optional": false,
            "inputParameters": {
              "terminationStatus": "FAILED",
              "workflowOutput": "${workflow.input}"
            }
          }
        ]
      }
    },`

**Comment by apanicker-nflx** [comment]
@btafarelo This issue is because of a bug in the case where a Terminate task within a Decision branch is executed. In the above case, the workflow ran correctly and terminated at the desired terminate task. However, the decision task was not saved correctly to the data store. The other branch of the decision tree was not executed but is bolded because of a UI glitch.

[This issue has been fixed](https://github.com/Netflix/conductor/pull/2093) and will be released soon.
