### ISSUE TITLE
Unable to update non system task status to IN_PROGRESS through POST /tasks API

### ISSUE THREAD

**Issue by jmanali** [Netflix/conductor#2108]
When we are trying to update task status to **IN_PROGRESS** from **SCHEDULED** through POST /tasks API, it returns task ID with 200 response but the task status still remains in SCHEDULED state. This was working earlier however the mentioned PR seems to have below code snippet and hence it is not allowing us to change the status to IN_PROGRESS

 if (!isSystemTask.test(task) && taskResult.getStatus() == Status.IN_PROGRESS) {
            task.setStatus(SCHEDULED);
        } else {
            task.setStatus(valueOf(taskResult.getStatus().name()));
        }

PR - https://github.com/Netflix/conductor/commit/8f0cf4463867257efcbd61

Can somebody please help us on this? Thank you!

**Comment by apanicker-nflx** [comment]
@jmanali This was done by design. Updating the status of a task from SCHEDULED to IN_PROGRESS is the responsibility of the state machine and is not exposed to the user. 

A given task will be moved from SCHEDULED to IN_PROGRESS when it is polled by the worker using the /tasks/poll/{taskType} API. At this point, it is expected that the worker is processing this task and will report back the result of the task to the POST /tasks API.

The lines mentioned above in your post are used in the case where the worker deems the task to be active and needs to process it at a later time. In this case, the worker returns the task as-is with a `callbackAfterSeconds` duration set to the period for which the task will be made invisible/unavailable to the worker. At this time, the task is set to SCHEDULED state in the server. Once this time expires, the task is available to be polled by the worker and will be put back to IN_PROGRESS when delivered to the worker.
