### ISSUE TITLE
Advice on how to properly construct a workflow that is inherently recursive

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#2110]
I am responsible for running and maintaining the Conductor instances in my organization. I have had a few teams in my organization that have created 'recursive' workflows that have caused major issues for Conductor. They have workflows that do things like check a status in their database and if the status is not what they want then their workflow calls itself as a subworkflow and so on and so on until the status is what they want. 

This causes StackOverflow errors when Conductor is 'deciding' the lowest level subworkflow because it has to walk the parent chain and there could be over a hundred levels of parent/child from bottom to top. It also adds a workflow to the _deciderQueue of Postgres every time so Conductor has to 'decide' on every one of the subworkflows as well as the original workflow itself. Eventually this _deciderQueue gets really large if they have a lot of workflows because each workflow could live for months.

Given this problem domain, one of the solutions we have come up with is to spawn a fresh workflow with the same correlation id and look up all the workflows with the same correlation id to diagnose what is going on with the one logical workflow. This is not palatable to one of the teams as they want a tree of workflows to traverse from top to bottom to see the history. It also does not solve the problem of the _deciderQueue growing to an unmanageable size.

In some business problems, we can use a workflow that uses a WAIT task and have an external service that checks the database status and COMPLETEs the WAIT task when the status is right. Unfortunately that doesn't solve other similar but not so simple situations.

Has anyone tackled a similar problem and come up with a good template solution?

BTW, one of the teams mentioned used a DO_WHILE task for this purpose about a year ago and had so many problems with it that they don't want to go down that path...

**Comment by aravindanr** [comment]
I see two separate problems listed here. We are aware of the bottlenecks that a large __deciderQueue_ could cause. We are exploring ways to split the queue and also options to scale up processing corresponding to __deciderQueue_ depth. These improvements are expected in Q3.2021.

Lately, we have seen problems with Subworkflows inside a FORK_JOIN, which led us to reevaluate how child workflows interact with the parent workflow. We are looking to move away from subworkflows traveling up the graph and _deciding_ the parent.  We are planning to make the _'decide'_ process asynchronous where the sub workflow only updates the subworkflow task in the parent, but does NOT call _decide_ on it. The parent workflow will be decided when the sweeper picks it up. This should avoid the Stackoverflow errors that can happen with recursion. This is in active development and will be released in Q1.2021.

Also, we are curious to know what problems that your team ran into with `DO_WHILE` task?

**Comment by apanicker-nflx** [comment]
> I have had a few teams in my organization that have created 'recursive' workflows that have caused major issues for Conductor. They have workflows that do things like check a status in their database and if the status is not what they want then their workflow calls itself as a subworkflow and so on and so on until the status is what they want

This is a rather strange implementation.  Have you considered using the callbackAfterSeconds mechanism instead? In this case, the worker would return the task as IN_PROGRESS with a desirable value for `callbackAfterSeconds` in the TaskResult object till the status in the db is not as expected for the task to be COMPLETED. This would mean that the same task instance is reused by the worker. The `callbackAfterSeconds` duration means that this particular task instance will be made invisible by the conductor server for this duration and be made available to be polled and executed after. This is quite a common use-case in our system and has been employed in a large number of long-running workflows by our users. [This section in the documentation](https://netflix.github.io/conductor/tasklifecycle/#timeout-seconds) expands on this to some extent.

>tree of workflows to traverse from top to bottom to see the history

As part of the above mechanism, the worker could choose to add a TaskExecutionLog to the TaskResult upon every poll/process, thereby maintaining a history of executions.

**Comment by rickfish** [comment]
I take back my comment about the DO_WHILE loop task statuses not being visible in the UI. Looks like that is working great now.

**Comment by apanicker-nflx** [comment]
Thanks for the additional context, for this use-case a DO_WHILE does look to be a better fit. Alternatively depending on the nature of the logical decision (whether it could be modeled as an independent subworkflow), you could use trigger a new workflow in every iteration which operates independently in a fire-and-forget manner.

**Comment by maheshyaddanapudi** [comment]
Hi,

Below is my understanding of the usecase.

Trigger Workflow 'Perform HC'

1) Start
2) Check Status
  2.1) If Status is Green --> Terminate with Status COMPLETED or just Stop (as in let the workflow end)
  2.2) If Status is Amber (as in not Green) --> Repeat

Instead of using a SUB_WORKFLOW, it can be replaced with a HTTP Task that would POST a request to run 'Perform HC'.

Something like below

Trigger Workflow 'Perform HC'

1) Start
2) Check Status
  2.1) If Status is Green --> Terminate with status COMPLETED or just Stop (as in let the workflow end)
  2.2) If Status is Amber (as in not Green) --> HTTP Task (call Trigger Workflow 'Perform HC') --> Terminate (With status FAILED)

And while checking if the HC was successful, a GET request to the API with a correlationId as search parameter can give the latest status.

This way a workflow's latest run always has the current status which can simply be determined by the workflow latest execution instance status itself.
  --> COMPLETED would mean the HC was successful
  --> FAILED would mean the latest check was unsuccessful
  --> IN_PROGRESS would mean , the check is in progress as the previous run FAILED.

Though it might increase the number of workflow executions, I think this would avoid the StackOverFlow error or anything similar.

Thanks and Regards,
Mahesh Yaddanapudi.

**Comment by rickfish** [comment]
Thanks. This is a good solution, very similar to using EVENT tasks to start the secondary workflow. We will look into this.
