### ISSUE TITLE
elasticsearch: workflow and task are not loading from dynomite/redis for the processing after the es node crash

### ISSUE THREAD

**Issue by hjha287** [Netflix/conductor#284]
I have an elasticsearch node which is running in a docker container and got crashed. After instantiating a new elasticsearch docker container, I can't pull the existing workflows using the search api (/workflow/search) though the data is present in dynomite/redis backend but when I pull a specific workflow with ID (/workflow/{workflowId}) then it works. could you please explain this behavior? And is there any way to get the scheduled tasks present in dynomite back for processing in newly es node. Thanks in advance

**Comment by v1r3n** [comment]
search goes through the elasticsearch - so if es the cluster is not available, the search will fail and not return results.  operations to retrieve workflow by ID goes through redis/dynomite which does not need ES.

Either way, elasticesarch is not used to process any data - so failure in es should not cause workflows to fail.

**Comment by hemant-jha** [comment]
It is totally fine if search does not work when ES cluster not available. But once ES cluster is back to operation after the failure (Instantiated the new ES node), it is not pulling the workflow data from the backend (dynomite/redis).

Because of this I am facing problem with conductor-ui. UI is not showing "All, running, Failed, Timed out etc" and not able to pause the task from UI. 

So my question is there any way to restore the ES after the crash so that UI could pull all workflows present in the backend.

**Comment by hjha287** [comment]
ES backup and restore from the backup after the failure should work in this case.
