### ISSUE TITLE
HTTP error response format has change in latest version (3.4.2)

### ISSUE THREAD

**Issue by minhas270** [Netflix/conductor#2904]
**Describe the bug**

After migrated from 2.x version to 3.4.2 there is HTTP error response has been changed, when we request result, there is no proper error response object in workflow.getOutput. Before in 2.x version we get proper map object(Follow the below Example) and now we get String response.

This was old version response(2.x)
`{
	response = {
		headers = {
			date = [Thu, 31 Mar 2022 08: 29: 02 GMT],
			server = [uvicorn],
			transfer - encoding = [chunked],
			clientid = [abc],
			content - type = [application / json],
			correlationid = [b4d81094 - ad36 - 4072 - 834a - eba568adea02]
		},
		reasonPhrase = Bad Request,
		body = {
			code = 04 - 00 - 00010,
			message = {
				value = dataObject field is null or blank,
				language = en
			}
		},
		statusCode = 400
	}
}
`

In the latest version(3.4.2V) we get same response into String object

`response -> java.lang.Exception: 400 Bad Request: [{"code":"04-00-00010","message":{"value":"dataObject field is null or blank","language":"en"}}]
`

[Exception Link
](https://github.com/Netflix/conductor/blob/5baca8d5c95d72b787f06e4e4e6baeb915ab0d8f/contribs/src/main/java/com/netflix/conductor/contribs/tasks/http/HttpTask.java#L145)

[Exception Throw Link](https://github.com/Netflix/conductor/blob/5baca8d5c95d72b787f06e4e4e6baeb915ab0d8f/contribs/src/main/java/com/netflix/conductor/contribs/tasks/http/HttpTask.java#L168)

**Details**
Conductor version: 3.4.2

**To Reproduce**
Request and provide invalid dataObject for HTTP task.
Request result for workflow.
Compare response with both version in workflow.getOutput 

**Expected behavior**
Map object

**Comment by apanicker-nflx** [comment]
Looking at the code in [v2.31](https://github.com/Netflix/conductor/blob/2.31/contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java#L143) the exception was converted to string and added to response object in the task output. This is similar to the code in v3.x now as seen in the link you posted above. Please let me know if i missed something.

**Comment by minhas270** [comment]
> Looking at the code in [v2.31](https://github.com/Netflix/conductor/blob/2.31/contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java#L143) the exception was converted to string and added to response object in the task output. This is similar to the code in v3.x now as seen in the link you posted above. Please let me know if i missed something.


Yes exception code is still same but httpCall method code has been updated in [v3.x](https://github.com/Netflix/conductor/blob/5baca8d5c95d72b787f06e4e4e6baeb915ab0d8f/contribs/src/main/java/com/netflix/conductor/contribs/tasks/http/HttpTask.java#L168) and [v2.31](https://github.com/Netflix/conductor/blob/2.31/contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java#L153)


So when we debug([v3.x]) and the exception throws error from "[restTemplate.exchange](https://github.com/Netflix/conductor/blob/5baca8d5c95d72b787f06e4e4e6baeb915ab0d8f/contribs/src/main/java/com/netflix/conductor/contribs/tasks/http/HttpTask.java#L168)" and that is why the response is different from previous version(v2.31)

**Comment by apanicker-nflx** [comment]
>So when we debug([v3.x]) and the exception throws error from "[restTemplate.exchange](https://github.com/Netflix/conductor/blob/5baca8d5c95d72b787f06e4e4e6baeb915ab0d8f/contribs/src/main/java/com/netflix/conductor/contribs/tasks/http/HttpTask.java#L168)" and that is why the response is different from previous version(v2.31)

Can you please share the exception thrown by the restTemplate.exchange method to help with debugging this issue? From the [implementation](So when we debug([v3.x]) and the exception throws error from "[restTemplate.exchange](https://github.com/Netflix/conductor/blob/5baca8d5c95d72b787f06e4e4e6baeb915ab0d8f/contribs/src/main/java/com/netflix/conductor/contribs/tasks/http/HttpTask.java#L168)" and that is why the response is different from previous version(v2.31)), for a 400 response the response will be populated and no exception should be thrown by the rest template.

**Comment by fscorro** [comment]
I have something similar with the new release (v.3.9.0). The response from the API is:

`2022-06-23 15:14:43.497 - INFO 81375 ----- [nio-8078-exec-9] ar.com.plug.util.filter.LoggingFilter    : {
  "method" : "GET",
  "path" : "/accounts-api/accounts/routings/schema/label",
  "status" : 417,
  "inDate" : 1656008083409,
  "outDate" : 1656008083491,
  "headers" : "[accept:application/json][content-type:application/json][host:host.docker.internal:8078][connection:Keep-Alive][user-agent:Apache-HttpClient/4.5.13 (Java/11.0.15)][accept-encoding:gzip,deflate]",
  "response" : "{\"code\":\"AC30\",\"debugMessage\":\"Non-existent routing\",\"message\":\"Non-existent routing\",\"status\":\"EXPECTATION_FAILED\",\"timestamp\":\"2022-06-23T18:14:43.482\"}",
  "remoteAddress" : "127.0.0.1"
}  `

But we're obtaining an exception in Conductor:

`"outputData": {
    "response": "java.lang.Exception: 417 : \"{\"status\":\"EXPECTATION_FAILED\",\"timestamp\":\"2022-06-23T18:14:43.482\",\"code\":\"AC30\",\"message\":\"Non-existent routing\",\"debugMessage\":\"Non-existent routing\"}\""
  },`

is it the expected behavior?

In case if it could help, here is the stacktrace:

`conductor-server_1  | 1109858 [system-task-worker-2] ERROR com.netflix.conductor.tasks.http.HttpTask [] - Got unexpected http response - uri: http://host.docker.internal:8078/accounts-api/accounts/routings/schema/label, vipAddress: null
conductor-server_1  | org.springframework.web.client.HttpClientErrorException: 417 : "{"status":"EXPECTATION_FAILED","timestamp":"2022-06-23T18:29:06.996","code":"AC30","message":"Non-existent routing","debugMessage":"Non-existent routing"}"
conductor-server_1  | 	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:145) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at com.netflix.conductor.tasks.http.HttpTask.httpCall(HttpTask.java:170) ~[conductor-http-task-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.tasks.http.HttpTask.start(HttpTask.java:104) ~[conductor-http-task-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.AsyncSystemTaskExecutor.execute(AsyncSystemTaskExecutor.java:137) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.tasks.SystemTaskWorker.lambda$pollAndExecute$1(SystemTaskWorker.java:145) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
conductor-server_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
conductor-server_1  | 1109859 [system-task-worker-2] ERROR com.netflix.conductor.tasks.http.HttpTask [] - 417 : "{"status":"EXPECTATION_FAILED","timestamp":"2022-06-23T18:29:06.996","code":"AC30","message":"Non-existent routing","debugMessage":"Non-existent routing"}"
conductor-server_1  | org.springframework.web.client.HttpClientErrorException: 417 : "{"status":"EXPECTATION_FAILED","timestamp":"2022-06-23T18:29:06.996","code":"AC30","message":"Non-existent routing","debugMessage":"Non-existent routing"}"
conductor-server_1  | 	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:145) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602) ~[spring-web-5.3.19.jar!/:5.3.19]
conductor-server_1  | 	at com.netflix.conductor.tasks.http.HttpTask.httpCall(HttpTask.java:170) ~[conductor-http-task-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.tasks.http.HttpTask.start(HttpTask.java:104) ~[conductor-http-task-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.AsyncSystemTaskExecutor.execute(AsyncSystemTaskExecutor.java:137) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.tasks.SystemTaskWorker.lambda$pollAndExecute$1(SystemTaskWorker.java:145) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
conductor-server_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
conductor-server_1  | 1109859 [system-task-worker-2] ERROR com.netflix.conductor.tasks.http.HttpTask [] - Failed to invoke HTTP task: 1915899b-717a-45a5-a6cf-5581c5bc0183 - uri: http://host.docker.internal:8078/accounts-api/accounts/routings/schema/label, vipAddress: null in workflow: a6f25ba6-a339-4311-adb8-f9461d4d94bd
conductor-server_1  | java.lang.Exception: 417 : "{"status":"EXPECTATION_FAILED","timestamp":"2022-06-23T18:29:06.996","code":"AC30","message":"Non-existent routing","debugMessage":"Non-existent routing"}"
conductor-server_1  | 	at com.netflix.conductor.tasks.http.HttpTask.httpCall(HttpTask.java:187) ~[conductor-http-task-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.tasks.http.HttpTask.start(HttpTask.java:104) ~[conductor-http-task-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.AsyncSystemTaskExecutor.execute(AsyncSystemTaskExecutor.java:137) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.tasks.SystemTaskWorker.lambda$pollAndExecute$1(SystemTaskWorker.java:145) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
conductor-server_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
conductor-server_1  | 1109864 [system-task-worker-2] INFO  com.netflix.conductor.core.execution.WorkflowExecutor [] - Execution terminated of workflow: a6f25ba6-a339-4311-adb8-f9461d4d94bd
conductor-server_1  | com.netflix.conductor.core.exception.TerminateWorkflowException: Failed to invoke HTTP task due to: java.lang.Exception: 417 : "{"status":"EXPECTATION_FAILED","timestamp":"2022-06-23T18:29:06.996","code":"AC30","message":"Non-existent routing","debugMessage":"Non-existent routing"}"
conductor-server_1  | 	at com.netflix.conductor.core.execution.DeciderService.retry(DeciderService.java:535) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:203) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.DeciderService.decide(DeciderService.java:119) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.WorkflowExecutor.decide(WorkflowExecutor.java:1302) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.AsyncSystemTaskExecutor.execute(AsyncSystemTaskExecutor.java:174) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at com.netflix.conductor.core.execution.tasks.SystemTaskWorker.lambda$pollAndExecute$1(SystemTaskWorker.java:145) ~[conductor-core-3.10.0-SNAPSHOT.jar!/:3.10.0-SNAPSHOT]
conductor-server_1  | 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
conductor-server_1  | 	at java.lang.Thread.run(Unknown Source) [?:?]
conductor-server_1  | 1109868 [system-task-worker-2] INFO  com.netflix.conductor.core.execution.WorkflowExecutor [] - Workflow a6f25ba6-a339-4311-adb8-f9461d4d94bd is terminated because of Failed to invoke HTTP task due to: java.lang.Exception: 417 : "{"status":"EXPECTATION_FAILED","timestamp":"2022-06-23T18:29:06.996","code":"AC30","message":"Non-existent routing","debugMessage":"Non-existent routing"}"`

**Comment by aravindanr** [comment]
@fscorro The call returns a `417` status code. Its not a successful response and thats why Conductor throws an exception. Am i missing something?

**Comment by indra-kargo** [comment]
hey, I have the same issue any alternative to evaluate the HTTP error response, since the format is inconsistent with the success response?
