### ISSUE TITLE
Memory in Kubernetes pod is not getting released

### ISSUE THREAD

**Issue by Sujay008** [Netflix/conductor#2930]
**Describe the bug**
JVM Memory consumed (In a kubernetes pod) is not getting released.

**Details**
Conductor version: 2.30.3
Persistence implementation: Postgres
Queue implementation: Postgres
Workflow definition: N/A
Task definition: N/A
Event handler definition: N/A

**Expected behavior**
We are using Conductor version 2.30.3 and running conductor in a k8s container. Now, when we have multiple workflows executed - we see that conductor memory is being consumed which is fine. However, we do observed that JVM is not releasing any memory consumed by conductor. In our case, each parent workflow will call multiple sub-workflow with each sub-workflow has some system / custom tasks. 

Load Placed - 4 Parallel execution and k8s pod resource limit are 1 Gi of memory.

**Screenshots**
![image](https://user-images.githubusercontent.com/37322064/163937846-52607736-f83c-4f9c-84fa-f7322c2a6843.png)

**Additional context**

**Comment by jxu-nflx** [comment]
Hello @Sujay008 workflows are loaded into memory when it is being evaluated and should be released once that's done. You might want to check the status of your workflow to understand what's going on there, is the workflow progressing? 4 parallel execution of workflows take up 1G of memory is crazy, do you have very large payload in your workflow?

**Comment by dongminglei** [comment]
> **Describe the bug** JVM Memory consumed (In a kubernetes pod) is not getting released.
> 
> **Details** Conductor version: 2.30.3 Persistence implementation: Postgres Queue implementation: Postgres Workflow definition: N/A Task definition: N/A Event handler definition: N/A
> 
> Steps to reproduce the behavior:
> 
> **Expected behavior** We are using Conductor version 2.30.3 and running conductor in a k8s container. Now, when we have multiple workflows executed - we see that conductor memory is being consumed which is fine. However, we do observed that JVM is not releasing any memory consumed by conductor. In our case, each parent workflow will call multiple sub-workflow with each sub-workflow has some system / custom tasks.
> 
> Load Placed - 4 Parallel execution and k8s pod resource limit are 1 Gi of memory.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/37322064/163937846-52607736-f83c-4f9c-84fa-f7322c2a6843.png)
> 
> **Additional context**

Can you provide the image and yam?  thank you

**Comment by flavioschuindt** [comment]
Hi, @jxu-nflx, I am helping @Sujay008 on that and here are some updates:

We bumped conductir version to 3.7.3, conducted the same tests and those are our observations:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/766004/194676860-cc0a1128-ed74-4da6-8aa2-e836c1ae8652.png">

* 1 replica (yellow curve): Memory tops at 1.4GB and is not released after my test. Eventually conductor crashes.
* Then, we went ahead and upscaled conductor horizontally in Kubernetes with 2 replicas (purple and pink curves). Initially seems that they are sharing the load, but eventually I tops again in the 1.4GB and conductor stops to respond simple API calls. This is because conductor is on the JVM Heap limits and of course, will crash soon.
* Finally, we upscaled it to 4 replicas and we see the two new replicas immediately going to 1.4GB.
* Our memory configuration for the POD in Kubernetes:

    <img width="155" alt="image" src="https://user-images.githubusercontent.com/766004/194676919-abf8e30a-ad1e-4cde-8201-c736ec1312c6.png">

* Our JVM configuration for conductor: ```-Xms256m -Xmx1024m```
* The size of the data that flows into the workflow is around 100MB. **Yes, we know this is a little bit high, but even in this case why the memory goes so crazy? More importantly: It accumulates and don't release even when system is idle**. By not releasing, things stay in the very limit and with just a new single execution crashes happen.
* In the end, the crashes are happening because of the limit close to 1536Mi which also means they are close to the Heap Max of 1GB.

In the end, we really don't know why conductor keeps accumulating the data in memory. If you see the yellow curve it has around 20 hours in idle and we would expect this memory to goes down. It simply does not happen.

P.S.: Yes, we know about the workflow/tasks limits and external payload size, but we were checking conductor code and the version that we are using has a bug that never terminates the workflow. This bug is already fixed in #3055, but unfortunately, we can't update conductor version at this moment.

**Comment by flavioschuindt** [comment]
So, we got another environment, kept the conductor replicas with just one and started to do the same test again and we are observing weird behaviors:

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/766004/195003841-b6b66556-94c3-4858-83a9-a05e9ad88cdb.png">

So, see in above curve you see:

* **From 17:06 to 20:09**: Normal behavior. Conductor started , uses around 477MB and system is idle. All good here;
* **From 20:09 to 20:23**: Weird behavior. At this time we just did some get workflows executions by ID. Seems that conductor loaded all of the execution data in memory and this does not get released. This bumps the memory from **497MB** to **614MB**. How is this possible?
* **From 20:23 to 20:51**: Another weird behavior. At this time we just did again another get workflows executions by ID. Seems that conductor loaded all of the execution data in memory again and this does not get released. This bumps the memory from **614MB** to **842MB**. Again: How is this possible?
* **At 20:53**: Another weird behavior. This time we just tried to delete the workflow execution and the memory bump again from **842MB** to **1.24GB**.

@jxu-nflx could you please reopen this ticket? The system is idle, no one is using, only us doing those basic tests and we are observing those behaviors. We believe there is some bug here. Any thoughts?

**Comment by lokeshcse6** [comment]
Memory occupied by Kubernetes pod is not getting released while jvm GC is happening properly, and pod memory never comes down even the service is in idle state.

I am also facing the same issue with java services which are deployed on K8s
Environment:
Docker: 19.03.11
Kubernetes: v1.23.7
openjdk version "1.8.0_342"
java parameters used 
java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=4 -XX:+UseContainerSupport -Xmx130m -Xms70m

JVM heap graph 

![visual](https://user-images.githubusercontent.com/84437898/222069198-74b6de29-32eb-40f1-84a5-380fa2ef8cee.JPG)

Pod memory usage:
![Capture](https://user-images.githubusercontent.com/84437898/222069495-473be644-574a-4e62-8905-eff463594b42.JPG)

could we reopen this ticket.

**Comment by rgrajan** [comment]
@lokeshcse6 Are you able to identify the issue? I am seeing something similar where JAVA microservices are running in the pods but not releasing the memory. But the GC is happening within JVM.
