### ISSUE TITLE
HTTP SystemTask vs. Worker task

### ISSUE THREAD

**Issue by shanemsully** [Netflix/conductor#341]
Is there any recommendation/experience w.r.t. using the HTTP system task vs. implementing a worker to execute tasks?  I didn't see anything in the docs besides the mechanics.

Are there any advantages or disadvantages to consider when choosing between the task types?

**Comment by svx94** [comment]
Having the same question...

My read from the doc is that System tasks are run in the same JVM as the conductor.  If your API is hosted in a separate container (which it should for scalability and performance tuning), they should be called through the worker task.  The system task is the "control language" that manage the flow, conditions, folks, joints, etc.  However, I got confused by the following in the System task:

DYNAMIC - **_A worker task_** which is derived based on the input  expression to the task, rather than being statically defined as part of  the blueprint.

So, looking for guidance as well...

**Comment by yandaxin** [comment]
Hello,I have a question:
how to connect Worker task to my own microservice,for example a python code file?
thanks!

**Comment by nakulm95** [comment]
Tagging along for the ride for this answer. Are there any examples of what constitutes as a worker task? The only thing I could pick up from the docs was "encoding a file" as an example, which made sense in the context. But, when deciding between a HTTP task and a worker task for making a request to an endpoint, which is recommended over the other?

**Comment by bstout** [comment]
@nakulm95 Using an HTTP task you'll define the URL where you make the call out to the service.  So, the service URL is part of your workflow.  But, with a task that polls, that polling worker can come and go and be on different machines and fulfill the request w/out changes to your WF if the URL changes

**Comment by kishorebanala** [comment]
We'll update the docs with best practices for system task vs worker task.

At high level, system tasks are executed by conductor server, and they shouldn't generally be computationally intensive. Whereas worker tasks can be scaled out and distributed to worker nodes.
