### ISSUE TITLE
Elasticsearch removal of workflows

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#352]
Hi,

Is there a reason why in Elasticsearch we retain the workflow index even after removing it via conductor API?  It seems like we remove it from the database but it is still remaining in Elasticsearch.  Is this a bug or expected?

**Comment by clari-akhilesh** [comment]
I believe it is kept there because when deleting workflows, they're removed from Redis but archived in ES. If the workflow is removed from the index, there is no way to lookup the workflow from the archive.
I have a PR which makes archiving optional. If the workflow is not being archived, it will be removed from the index as well. This will remove the workflow completely from the system. Please refer to https://github.com/Netflix/conductor/pull/381 for more details.

**Comment by v1r3n** [comment]
Closing this based on the PR from @clari-akhilesh
