### ISSUE TITLE
Triggering workflow with "Accept: application/json" fails with "406 Not Acceptable"

### ISSUE THREAD

**Issue by GregorioDiStefano** [Netflix/conductor#376]
Conductor 1.8.1

Triggering a workflow that includes the "Accept: application/json" header returns "HTTP/1.1 406 Not Acceptable" which obviously doesn't make sense, since JSON is the returned payload in some instances (a failed trigger, for example, returns JSON, while a successful triggering results in a simple UUID in plaintext)

**Comment by themaxx76** [comment]
Any news on this? This issue caused us a lot of troubles before have found this info.

**Comment by kishorebanala** [comment]
@themaxx76 This still is the case, as the endpoint accepts the header "Accept: text/plain".

In order to move from text/plain to application/json, we'd have to change the return format of this endpoint, without breaking backwards compatibility for existing uses. We shall prioritize this for Conductor 3.0 release, but feel free to send us a proposal if you can get to this before that.
