### ISSUE TITLE
Confusion around queues.dynomite.nonQuorum.port

### ISSUE THREAD

**Issue by fozboz** [Netflix/conductor#406]
I am setting up a HA Conductor cluster and am confused about `queues.dynomite.nonQuorum.port` setting. I'm using a dynomite backend. The documentation says:

`For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite`

Why does Conductor need to know which port Redis is listening on when it's behind Dynomite?

On the dynomite hosts I have redis listening only on localhost:6379 and Dynomite then proxying to that, which feels to me the sanest, most secure approach. Am I missing something?

**Comment by shailesh33** [comment]
The problem is Dynomite is used in a quorum setting, and when conductor tries to get a cardinality of the queue (length) it cannot achieve quorum since data might be in a flux. Dynomite does not provide connection/query level quorum settings. Hence a work around was to let dynomite talk to redis to get the length. Completely agree on your 'sanest' comment.
