### ISSUE TITLE
What is the usecase of MySQLQueueDAO class in Mysql persistence module?

### ISSUE THREAD

**Issue by akshat-g** [Netflix/conductor#603]
Naive question, but I need to understand what purpose and what flows are run via MySQLQueueDAO class? I can see push, pop, pollmessages method in the class. Where are they pushing, pulling and popping from?
Any help would be appreciated.
Thanks

**Comment by gsambasiva** [comment]
@akshat-g , we have a class called SystemTaskWorkerCoordinator it will fetch tasks from queues.
In **listen()** method.


And before that, whenever we start a workflow it will invoke a method startWorkflow method of WorkflowExecutor class.
And here is the flow of methods, to understand, how it is going to insert into queue.

startWorkflow() -> decide() -> scheduleTask() -> addTaskToQueue()

**Comment by jvemugunta** [comment]
Not sure about your question.
If you don't want to run on cloud with dynomite and want to run on Perm, you can use MYSQL as the underlying storage

**Comment by mashurex** [comment]
@akshat-g since Conductor is designed around queues of work using NoSQL/non-relational storage (Dynomite/Redis) the QueueDAO interface must be implemented for any new persistence module. The MySQLQueueDAO is an implementation of the QueueDAO interface that uses MySQL tables and queries to implement the same functionality that Dynomite and Redis queues would provide.

**Comment by apanicker-nflx** [comment]
Closing since this is already answered.
