### ISSUE TITLE
Conductor and Dynomite setup related questions for moving away from  SWF

### ISSUE THREAD

**Issue by krisch93** [Netflix/conductor#704]
Hi, 
We are trying to move away from AWS SWF in our project and we are currently exploring various suitable options and conductor seems to be a better alternative.

Can you please help us clarify some of the below mentioned points so that we can get a better understanding of conductor ??

-  For the conductor configuration “workflow.dynomite.cluster.hosts”, do we need to mention all of the dynamite hosts?
       If so , is it ok to keep dns host names instead of IP address so that we don’t have to update the 
       conductor config even if a nodes goes down and other comes up… 

-What is the role of Elastic search in conductor setup - is it solely for the purpose of indexing the  "In Progress" workflows so that searching them can be easier from the UI ?
     If so, then can we get rid of ES if one does not require UI ??

- What is the minimum recommended number of nodes for running dynomite to achieve HA ?

- Do we need to mention all the nodes in the dynamite cluster except the current one for the configuration dyn_seeds in dynomite ? 
    And can we use dns host names instead of ip addresses with dyn_seed_provider as simple_provider ?

- What consistency level of dynamite would you suggest for conductor setup ?

- How would the data recovery happen to one of the nodes in the dynamite cluster if it goes down and another comes up in its place ?

- What happens when the replication is 3 and one of the node containing that replica is down during a read?

- How the quorum works when we one of the nodes is down (cluster of 3) during a write ?

- Are there any Performance Benchmarks related to Dyno Queue and Dynomite ?

**Comment by saidatta** [comment]
Here are my answers based on my experiences. Maybe someone else can answer your questions more accurately.
1) I believe you can mention dns names. 
2) - https://github.com/Netflix/conductor/issues/23
3) - I believe it is 3 nodes for HA 
4) & 5) - @ipapapa is more knowledgeable to answer the dyn_seeds question and consistency level
6) I believe the replication mechanisms are found in the dynomite docs / simalar to cassandra technicals.

**Comment by ipapapa** [comment]
* We run Dynomite in 1 node per rack, and 3 racks per datacenter. The level of HA you want to achieve depends on your business needs.
* Dyno-queues and Conductor require `DC_SAFE_QUORUM` to properly operate. You can find more about [consistency](https://github.com/Netflix/dynomite/wiki/Consistency).
* If a replica is down in another datacenter, it does not matter. If one node is down, in the same datacenter again there is no problem in any consistency setting
* If a node goes down, and new node comes up, Dynomite has the [warm-up feature](https://github.com/Netflix/dynomite-manager/wiki/Cold-Bootstraping). 
* Yes, we had made in the past some benchmarks on dyno-queues and Dynomite. We had a few in the following [blog post](https://medium.com/netflix-techblog/distributed-delay-queues-based-on-dynomite-6b31eca37fbc). Since then we have done a few optimizations, and the performance is way faster.

**Comment by ipapapa** [comment]
Here are a few data points from a performance benchmark we did a year ago: 

Msgs per Queue | Batch Size | Total Time to Drain (ms) | Throughput (msg / sec) | Recipe | Extrapolated time to drain 20M messages in secs
-- | -- | -- | -- | -- | --

5,050,000 | 1000 | 240547 | 20,994 | Dynomite | 962.188
-- | -- | -- | -- | -- | --
