### ISSUE TITLE
Callback After Question

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#71]
@v1r3n 
I am still having some problems to understand the feature "callback after" where you already provided some more details [here](https://github.com/Netflix/conductor/issues/9):

> When the worker updates the status of the task as IN_PROGRESS, it can optionally provide a time delay after which the task should be made available. This is useful for long running tasks where the worker should be periodically checking the status of the task completion (by another process for example) at a fixed interval (say 1 hour). Callback after value can be set by worker as part of the Task's status update.

Lets say, the "long running worker" polls for the task, updates it to IN_PROGRESS and additionally  with a callback of 1 hour.

What does it mean that the task would be made available again?
Is Conductor Server rescheduling the task after 1 hour if the worker is not finished? If yes, what's the difference then compared to the reagular timeout setting in the task definition?

What does it mean that the worker can periodically check the status for task completion?
In my understanding the worker "works as long as it needs" and Conductor Server is waiting for a task update with COMPLETED to check for task completion - why should the worker check for any status of task completion?

Thanks for any additional information, example or use case to help me better understand this feature.

**Comment by v1r3n** [comment]
@blueelephants 
Conductor uses delay queues for task workers.  When a task is updated with ```IN_PROGRESS``` status and a callbackAfter value greater than 0, the task is added back to the queue with the delay time same as ```callbackAfter``` value.  

When workers are polling for tasks, the given task will remain in the queue until the timeout.

This feature is useful (and used by us) for asynchronous tasks where the worker is not actually doing the task but rather scheduling it to run on another system.  

A good example is a task waiting for arrival of a file in s3 bucket.  Rather than running a tight loop, it can check if the file is present or not and return back with ```IN_PROGRESS```  status and callback time say 10 minutes.  The task is given back to the worker in 10 mins where it can check the file and completes if the file is present or returns back with ```IN_PROGRESS```  status.

Advantage here is that you avoid running a tight loop for checking the status and the work is distributed amongst workers - so if one of the worker dies, the task is picked up another one in the cluster.  (assuming HA deployment for the workers too)

Hope this helps.

**Comment by blueelephants** [comment]
Many thanks for your explanations
