### ISSUE TITLE
Workflow timeout

### ISSUE THREAD

**Issue by davidgodf** [Netflix/conductor#712]
Is there a way to set a timeout for the execution of a complete workflow? I can see how to do this at the task level, but I need to be able to specify that the complete workflow must either complete or be timed out after X seconds. I could see how I could handle this with additional logic in my client and tasks, but it would be nicer if there was some way to define it at the workflow level.

**Comment by apanicker-nflx** [comment]
Since the concept behind conductor is to asynchronously orchestrate the process flow, a timeout at a workflow level does not seem like a construct that fits in. Task level timeouts should be able to accomplish this if you still need to enforce this.

Closing this issue for now. Please reopen if you see a compelling need for this.
