### ISSUE TITLE
Any advice on versioning of workflows/tasks?

### ISSUE THREAD

**Issue by xaka** [Netflix/conductor#751]
The documentation is great! What I couldn't find though is information regarding the versioning. 

- What's Netflix take on it? Any best practices, patterns?
- Do I name my workflows/tasks like "workflow_v1/v2/..." and "task_v1/v2/..." and follow the same pattern for classes i.e. MyTaskV1, MyTaskV2, etc.? 
- What about the situation when I don't want to disrupt an existing (in progress) flow and yet release a new version at the same time?

Thanks!

**Comment by saidatta** [comment]
From my understanding & experience,
3) - Workers poll based on tasks rather than workflows. If there is an existing workflow using a worker node, and you restart it with updated code. Then, the on-going workflow will be effected with the changes. But, the portal for starting the workflow requires which version of that WF to start.

**Comment by apanicker-nflx** [comment]
@xaka With the changes to Conductor 2.0, any changes made to the workflow or task definitions after a workflow has been started will not affect the existing (RUNNING) workflows. The workflow and task definitions are locked in with the workflow execution.
With regards to versioning, use the `version` field within the workflow definition to differentiate/safeguard against changes as a best practice. Since tasks are intended to be used across multiple workflows, the overhead of maintaining task versions was not found to be justifiable. So in case you still need to do it, you could achieve this by what you mentioned earlier as naming the tasks `task_v1/v2` etc.
