### ISSUE TITLE
Serverless w/ Conductor?

### ISSUE THREAD

**Issue by saidatta** [Netflix/conductor#820]
Anyone using the Serverless architectures with Conductor? if yes, in what capacity? would love to know more.

**Comment by cyzhao** [comment]
You question is quite open and I am not sure what you really mean here, please clarify.

**Comment by saidatta** [comment]
I am not sure the exact scope of the question, but here are my few questions that I had in mind.

I was thinking of having some AWS Lambda functions implement my worker logic and have that poll conductor.
 I am not sure about the feasibility (as Lambda functions have 15 min limit
- AWS Lambda as workers for conductor. thoughts?
- contrast between Step Functions vs Conductor? 
- Is there a limit of Dynamically generated tasks in Conductor? Currently, I am dynamically generating 650 subtasks from a Dynamic Fork?

**Comment by cyzhao** [comment]
- We never looked into using AWS Lambda as workers, but keep in mind Conductor worker polls for tasks so it needs to be long running process.
- Analysis done by Shawn Xu: https://xunnanxu.github.io/2018/04/13/Workflow-Processing-Engine-Overview-2018-Airflow-vs-Azkaban-vs-Conductor-vs-Oozie-vs-Amazon-Step-Functions/
- Currently Conductor doesn't limit dynamic tasks but we are planning to add a limit because large number of dynamic tasks can cause performance issues.
