### ISSUE TITLE
Deploying conductor to PCF 

### ISSUE THREAD

**Issue by anandctrwork** [Netflix/conductor#865]
Hi, 

I would like to know if anyone deployed Conductor in PCF or any cloud platform.  Can it run as microservice?

Thanks
Kumar

**Comment by saidatta** [comment]
I mean, I deployed it to AWS using their EC2 machines, dynmoite/ Elasticache?

**Comment by davidwadden** [comment]
@anandctrwork  I don't know if i'd call it a "micro" service, but it runs on container platforms such as PCF/PWS, provided you can supply the Redis/MySQL and ES 5 backing services.  Just make sure to give it 1gb container size for Memory.

See https://github.com/davidwadden/conductor/commits/pws for patches I made that may be helpful.  This patch supports Redis authentication, places a config.properties into the JAR and re-indexes ES on start-up to support ephemeral Elasticsearch in-memory instance since finding ES5 with Transport Client in the wild is tough.

**Comment by anandctrwork** [comment]
> @anandctrwork I don't know if i'd call it a "micro" service, but it runs on container platforms such as PCF/PWS, provided you can supply the Redis/MySQL and ES 5 backing services. Just make sure to give it 1gb container size for Memory.
> 
> See https://github.com/davidwadden/conductor/commits/pws for patches I made that may be helpful. This patch supports Redis authentication, places a config.properties into the JAR and re-indexes ES on start-up to support ephemeral Elasticsearch in-memory instance since finding ES5 with Transport Client in the wild is tough.

Thanks David for the response

**Comment by anandctrwork** [comment]
> I mean, I deployed it to AWS using their EC2 machines, dynmoite/ Elasticache?

Ok, good to know
