### ISSUE TITLE
Why the returnTask method removed in Release 2.x from WorkflowTaskCoordinator.execute

### ISSUE THREAD

**Issue by JasperB** [Netflix/conductor#866]
Hi conductor team,

Anybody can help explain why the returnTask() method removed from WorkflowTaskCoordinator.execute() in release 2.0? we're using release 1.12, but just saw there is something different want double check, please help, thanks!

**Comment by apanicker-nflx** [comment]
[Here](https://github.com/Netflix/conductor/commit/169485b9223d5a518e516f2e973a8c8bc2aae772#diff-496ab628ec2175eb6539b2556b67f68dL366), the `returnTask` was removed upon ack failure or execution because if the ack fails or throws an exception, the task will be requeued by the server after the unack timeout. The task return is unnecessary.
