### ISSUE TITLE
Question on WorkflowExecutor

### ISSUE THREAD

**Issue by avikawale** [Netflix/conductor#88]
Hi ,
I have a question on how the WorkflowExecutor works. 
So in the WorkflowExecutor.java I see below lines.  
In the first line I am assuming you are storing the workflow in database. 
In the second line we are pushing the workflow to the queue. 
But once it is pushed to the queue why do we run line 3 locally and execute the workflow ? My thought was that the workflow id would be picked up from a queue by a listener and then executed asynchronously. 
Can you please shed some more light on this ? 

1) edao.createWorkflow(wf);

2) queue.push(deciderQueue, wf.getWorkflowId(), config.getSweepFrequency());	
	
3) decider.decide(workflowId, this);

**Comment by v1r3n** [comment]
Each time the workflow is created or task is updated, the state is evaluated at the same time and next set of tasks are scheduled (if required).  We do not use internal queueing for this.

There is an internal queue  that is used to "sweep" any state evaluations that did not complete (due to errors, jvm getting terminated etc.) and recomputes the same.

**Comment by v1r3n** [comment]
@avikawale let me know if this answers your question.  We can close the issue.
